### ISSUE TITLE
ArgoEvents not triggering the workflows show wrong ClusterID error

### ISSUE THREAD

**Issue by nvenkatapavan** [argoproj/argo-events#862] opened 2020-09-04 13:06 UTC
ArgoEvents not triggering the workflows. When We check the application sensor logs  it shows **wrong ClusterID** i have provided error logs also i have provided **argo-events-eventbus-controller**. Could someone please help us on it ?
It's blocking our deployments, thank you. 

Note:  We are running around 10 application, only one has this issue others are working fine and We are using app of apps concept in argocd to sync the sensor yaml files form github to cluster ( autodeploy any change in workflow). 

**kubectl logs aiops-sensor-4txdk-669977f886-b44nb -n argo-events**

`{"error":"stan: connect request timeout (possibly wrong cluster ID?)","level":"error","msg":"failed to reconnect to eventbus, client: client-720281588","time":"2020-09-01 09:52:58"}
{"level":"info","msg":"NATS connection lost, reconnecting...","time":"2020-09-01 09:53:01"}
{"clientID":"client-720281588","level":"info","msg":"NATS auth strategy: Token","time":"2020-09-01 09:53:01"}
{"clientID":"client-720281588","level":"info","msg":"Connected to NATS server.","time":"2020-09-01 09:53:01"}
{"clientID":"client-720281588","level":"error","msg":"Failed to connect to NATS streaming server, stan: connect request timeout (possibly wrong cluster ID?)","time":"2020-09-01 09:53:03"}
{"error":"stan: connect request timeout (possibly wrong cluster ID?)","level":"error","msg":"failed to reconnect to eventbus, client: client-720281588","time":"2020-09-01 09:53:03"}
{"level":"info","msg":"NATS connection lost, reconnecting...","time":"2020-09-01 09:53:06"}
{"clientID":"client-720281588","level":"info","msg":"NATS auth strategy: Token","time":"2020-09-01 09:53:06"}
{"clientID":"client-720281588","level":"info","msg":"Connected to NATS server.","time":"2020-09-01 09:53:06"}
{"clientID":"client-720281588","level":"info","msg":"Connected to NATS streaming server.","time":"2020-09-01 09:53:07"}
{"level":"info","msg":"reconnected to NATS streaming server for client client-720281588...","time":"2020-09-01 09:53:07"}
{"clientID":"client-720281588","level":"error","msg":"NATS connection lost, reason: \u003cnil\u003e","time":"2020-09-01 10:23:50"}
{"clientID":"client-720281588","level":"error","msg":"NATS connection lost, reason: \u003cnil\u003e","time":"2020-09-01 10:23:50"}
{"clientID":"client-720281588","level":"error","msg":"NATS connection lost, reason: \u003cnil\u003e","time":"2020-09-01 10:23:50"}
{"clientID":"client-720281588","level":"error","msg":"NATS connection lost, reason: \u003cnil\u003e","time":"2020-09-01 10:23:50"}
{"clientID":"client-720281588","level":"error","msg":"NATS streaming connection lost, reason: nats: connection closed","time":"2020-09-01 10:23:52"}`

 **kubectl logs argo-events-eventbus-controller-c4bcb9d58-5r7jh -n argo-events**

`2020-09-04T12:54:00.586Z	info	controller-runtime.metrics	metrics server is starting to listen	{"addr": ":8080"}
2020-09-04T12:54:00.586Z	info	eventbus-controller.main	starting manager
2020-09-04T12:54:00.587Z	info	controller-runtime.manager	starting metrics server	{"path": "/metrics"}
2020-09-04T12:54:00.587Z	info	controller-runtime.controller	Starting EventSource	{"controller": "eventbus-controller", "source": "kind source: /, Kind="}
2020-09-04T12:54:00.695Z	info	controller-runtime.controller	Starting EventSource	{"controller": "eventbus-controller", "source": "kind source: /, Kind="}
2020-09-04T12:54:01.396Z	info	controller-runtime.controller	Starting EventSource	{"controller": "eventbus-controller", "source": "kind source: /, Kind="}
2020-09-04T12:54:01.597Z	info	controller-runtime.controller	Starting EventSource	{"controller": "eventbus-controller", "source": "kind source: /, Kind="}
2020-09-04T12:54:01.698Z	info	controller-runtime.controller	Starting EventSource	{"controller": "eventbus-controller", "source": "kind source: /, Kind="}
2020-09-04T12:54:02.001Z	info	controller-runtime.controller	Starting Controller	{"controller": "eventbus-controller"}
2020-09-04T12:54:02.001Z	info	controller-runtime.controller	Starting workers	{"controller": "eventbus-controller", "worker count": 1}
2020-09-04T12:54:02.116Z	error	controller-runtime.controller	Reconciler error	{"controller": "eventbus-controller", "request": "argo-events/default", "error": "Operation cannot be fulfilled on eventbus.argoproj.io \"default\": the object has been modified; please apply your changes to the latest version and try again"}
github.com/go-logr/zapr.(*zapLogger).Error
	/home/runner/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.4/pkg/internal/controller/controller.go:247
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.4/pkg/internal/controller/controller.go:221
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.4/pkg/internal/controller/controller.go:200
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.17.6-beta.0/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.17.6-beta.0/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.17.6-beta.0/pkg/util/wait/wait.go:88`

**Comment by whynowy** [comment] 2020-09-04 15:57
What is the version?
Do you see any EventBus POD running?

**Comment by nvenkatapavan** [comment] 2020-09-05 12:33
@whynowy Thanks for replay 

We are using v0.17.0 vesion of argo-events
Yes, Acutally it shows all eventbus pods are running. But argo-events-eventbus-controller shows errors. 

argo-events-eventbus-controller-c4bcb9d58-5r7jh          1/1     Running   0          23h
eventbus-default-stan-0                                  2/2     Running   0          4d1h
eventbus-default-stan-1                                  2/2     Running   0          4d1h
eventbus-default-stan-2                                  2/2     Running   0          4d1h


`2020-09-04T15:27:00.425Z	error	controller-runtime.controller	Reconciler error	{"controller": "eventbus-controller", "request": "argo-events/default", "error": "Operation cannot be fulfilled on eventbus.argoproj.io \"default\": the object has been modified; please apply your changes to the latest version and try again"}
github.com/go-logr/zapr.(*zapLogger).Error
	/home/runner/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.4/pkg/internal/controller/controller.go:247
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.4/pkg/internal/controller/controller.go:221
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.4/pkg/internal/controller/controller.go:200
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.17.6-beta.0/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.17.6-beta.0/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.17.6-beta.0/pkg/util/wait/wait.go:88
E0904 16:40:48.374906       1 reflector.go:309] pkg/mod/k8s.io/client-go@v0.17.5/tools/cache/reflector.go:105: Failed to watch *v1.Service: Get "https://172.21.0.1:443/api/v1/services?allowWatchBookmarks=true&resourceVersion=8528826&timeoutSeconds=496&watch=true": unexpected EOF`

**Comment by whynowy** [comment] 2020-09-05 17:05
The error in eventbus-controller was caused by reconciliation race condition, it does not matter since the reconciliation keeps retrying if there's an error. 

Can you let me know if you eventsource POD runs ok (is there any NATS connection error)? And if you kill the sensor POD, will it work?

**Comment by nvenkatapavan** [comment] 2020-09-07 03:07
@whynowy 
Sometimes it worked if I kill sensor POD, but most of the time i was getting error saying **clientID already registered**. We don't have any other sensor running with same name. 

`{"level":"info","msg":"Dependency expression for trigger github-workflow-trigger before simlification: test-dep","time":"2020-09-07 02:56:56"}
{"level":"info","msg":"Dependency expression for trigger github-workflow-trigger after simlification: test-dep","time":"2020-09-07 02:56:56"}
{"level":"info","msg":"Sensor started.","time":"2020-09-07 02:56:56"}
{"clientID":"client-1964515521","level":"info","msg":"NATS auth strategy: Token","time":"2020-09-07 02:56:56"}
{"clientID":"client-1964515521","level":"info","msg":"Connected to NATS server.","time":"2020-09-07 02:56:56"}
{"clientID":"client-1964515521","level":"error","msg":"Failed to connect to NATS streaming server, stan: clientID already registered","time":"2020-09-07 02:56:56"}
{"error":"stan: clientID already registered","level":"error","msg":"Failed to connect to event bus","time":"2020-09-07 02:56:56"}`

**Comment by whynowy** [comment] 2020-09-07 04:08
I see. We had some EventBus connection reliability issues in v0.17.0, which have been fixed in the latest v1.0.0 release (see https://github.com/argoproj/argo-events/commit/8a102871df674278d7a3d3d3f16f59ffdf58cf72 and https://github.com/argoproj/argo-events/commit/f2411be5eb7b3018c1f84700a44ba29a9a48b90b). I would suggest you to migrate to the new version.

**Comment by whynowy** [comment] 2020-09-08 20:34
@nvenkatapavan - Please let me know if you have got chance switching to the latest version, and if things have got better.

**Comment by ptemmer** [comment] 2020-09-10 07:35
I'm using v1.0.0 and in my case neither of the sensor pods or eventsource pod is able to connect to the NATS Streaming server.
All show the same error, even after restarting the pods:

```
"level":"info","ts":1599719594.0572975,"logger":"argo-events.eventsource","caller":"driver/nats.go:104","msg":"Connected to NATS server.","eventSourceName":"webhook-event-source","clientID":"webhook-event-source-eventsource-wdr9l-647b856d7c-8nkmd"}
{"level":"error","ts":1599719596.072933,"logger":"argo-events.eventsource","caller":"driver/nats.go:114","msg":"Failed to connect to NATS streaming server","eventSourceName":"webhook-event-source","clientID":"webhook-event-source-eventsource-wdr9l-647b856d7c-8nkmd","error":"stan: connect request timeout (possibly wrong cluster ID?)"
```

The only way to "fix" the problem is to restart the NATS statefulset. Apparently though, the NATS server booted correctly.

eventbus-default-stan-0:
```
[1] 2020/09/10 05:23:11.323807 [INF] STREAM: Starting nats-streaming-server[eventbus-default] version 0.17.0
[1] 2020/09/10 05:23:11.468755 [INF] STREAM: ServerID: Xx4P2W7r6rNhSjV1ciwUYJ
[1] 2020/09/10 05:23:11.468762 [INF] STREAM: Go version: go1.13.7
[1] 2020/09/10 05:23:11.468767 [INF] STREAM: Git commit: [f4b7190]
[1] 2020/09/10 05:23:13.733527 [INF] Starting nats-server version 2.1.4
[1] 2020/09/10 05:23:13.733560 [INF] Git commit [fb009af]
[1] 2020/09/10 05:23:13.733801 [INF] Starting http monitor on 0.0.0.0:8222
[1] 2020/09/10 05:23:13.733868 [INF] Listening for client connections on 0.0.0.0:4222
[1] 2020/09/10 05:23:13.733875 [INF] Server id is NACMO5BOPKXLPW2JGTEDOACDQEBCKJSYAMMLNIZANKE43I7DMYX3FZRS
[1] 2020/09/10 05:23:13.733879 [INF] Server is ready
[1] 2020/09/10 05:23:13.734160 [INF] Listening for route connections on 0.0.0.0:6222
[1] 2020/09/10 05:23:13.753157 [INF] 10.161.13.15:6222 - rid:1 - Route connection created
[1] 2020/09/10 05:23:13.753308 [INF] 10.161.13.15:55540 - rid:2 - Route connection created
[1] 2020/09/10 05:23:13.770827 [INF] 10.161.13.15:6222 - rid:1 - Router connection closed
[1] 2020/09/10 05:23:13.770919 [INF] 10.161.13.15:55540 - rid:2 - Router connection closed
[1] 2020/09/10 05:23:13.843939 [INF] STREAM: Recovering the state...
[1] 2020/09/10 05:23:13.845182 [INF] STREAM: No recovered state
[1] 2020/09/10 05:23:13.845294 [INF] STREAM: Cluster Node ID : eventbus-default-stan-0
[1] 2020/09/10 05:23:13.845301 [INF] STREAM: Cluster Log Path: /data/stan/logs
[1] 2020/09/10 05:23:18.384193 [INF] STREAM: Message store is RAFT_FILE
[1] 2020/09/10 05:23:18.384222 [INF] STREAM: Store location: /data/stan/store
[1] 2020/09/10 05:23:18.384265 [INF] STREAM: ---------- Store Limits ----------
[1] 2020/09/10 05:23:18.384271 [INF] STREAM: Channels:                  100 *
[1] 2020/09/10 05:23:18.384274 [INF] STREAM: --------- Channels Limits --------
[1] 2020/09/10 05:23:18.384278 [INF] STREAM:   Subscriptions:          1000 *
[1] 2020/09/10 05:23:18.384281 [INF] STREAM:   Messages     :       1000000 *
[1] 2020/09/10 05:23:18.384284 [INF] STREAM:   Bytes        :     976.56 MB *
[1] 2020/09/10 05:23:18.384287 [INF] STREAM:   Age          :       72h0m0s
[1] 2020/09/10 05:23:18.384290 [INF] STREAM:   Inactivity   :     unlimited *
[1] 2020/09/10 05:23:18.384293 [INF] STREAM: ----------------------------------
[1] 2020/09/10 05:24:24.985551 [WRN] 127.0.0.1:44862 - cid:6 - Readloop processing time: 22.650015014s
[1] 2020/09/10 05:24:46.770946 [WRN] 127.0.0.1:44862 - cid:6 - Readloop processing time: 3.334474526
```

eventbus-default-stan-1:
```
[1] 2020/09/10 05:27:00.910370 [INF] STREAM: Starting nats-streaming-server[eventbus-default] version 0.17.0
[1] 2020/09/10 05:27:00.910876 [INF] STREAM: ServerID: 4hCrpmRv5OxPw63sPwQbCg
[1] 2020/09/10 05:27:00.910976 [INF] STREAM: Go version: go1.13.7
[1] 2020/09/10 05:27:00.964980 [INF] STREAM: Git commit: [f4b7190]
[1] 2020/09/10 05:27:01.000976 [INF] Starting nats-server version 2.1.4
[1] 2020/09/10 05:27:01.001019 [INF] Git commit [fb009af]
[1] 2020/09/10 05:27:01.005833 [INF] Starting http monitor on 0.0.0.0:8222
[1] 2020/09/10 05:27:01.005944 [INF] Listening for client connections on 0.0.0.0:4222
[1] 2020/09/10 05:27:01.005957 [INF] Server id is NDMN2LDITRYE2RV32ZV2TY6QLLWRFIJM7BITQ74BK6V6HJLY7R2RXGV2
[1] 2020/09/10 05:27:01.005961 [INF] Server is ready
[1] 2020/09/10 05:27:01.080336 [INF] Listening for route connections on 0.0.0.0:6222
[1] 2020/09/10 05:27:01.399383 [INF] 10.161.13.252:6222 - rid:3 - Route connection created
[1] 2020/09/10 05:27:01.399526 [INF] 10.161.13.252:60998 - rid:4 - Route connection created
[1] 2020/09/10 05:27:01.399682 [INF] 10.161.13.252:6222 - rid:3 - Router connection closed
[1] 2020/09/10 05:27:01.399820 [INF] 10.161.13.252:60998 - rid:4 - Router connection closed
[1] 2020/09/10 05:27:01.408881 [INF] STREAM: Recovering the state...
[1] 2020/09/10 05:27:01.409123 [INF] STREAM: No recovered state
[1] 2020/09/10 05:27:01.409211 [INF] STREAM: Cluster Node ID : eventbus-default-stan-1
[1] 2020/09/10 05:27:01.409217 [INF] STREAM: Cluster Log Path: /data/stan/logs
[1] 2020/09/10 05:27:01.930556 [INF] STREAM: Message store is RAFT_FILE
[1] 2020/09/10 05:27:01.930586 [INF] STREAM: Store location: /data/stan/store
[1] 2020/09/10 05:27:01.930637 [INF] STREAM: ---------- Store Limits ----------
[1] 2020/09/10 05:27:01.930643 [INF] STREAM: Channels:                  100 *
[1] 2020/09/10 05:27:01.930646 [INF] STREAM: --------- Channels Limits --------
[1] 2020/09/10 05:27:01.930650 [INF] STREAM:   Subscriptions:          1000 *
[1] 2020/09/10 05:27:01.930653 [INF] STREAM:   Messages     :       1000000 *
[1] 2020/09/10 05:27:01.930656 [INF] STREAM:   Bytes        :     976.56 MB *
[1] 2020/09/10 05:27:01.930659 [INF] STREAM:   Age          :       72h0m0s
[1] 2020/09/10 05:27:01.930663 [INF] STREAM:   Inactivity   :     unlimited *
[1] 2020/09/10 05:27:01.930676 [INF] STREAM: ----------------------------------
[1] 2020/09/10 05:29:04.995601 [WRN] 127.0.0.1:44098 - cid:6 - Readloop processing time: 2.42270083s
[1] 2020/09/10 05:59:00.681993 [WRN] 127.0.0.1:44098 - cid:6 - Readloop processing time: 3.948624332s
```

eventbus-default-stan-2:
```
[1] 2020/09/10 05:20:53.670751 [INF] STREAM: Starting nats-streaming-server[eventbus-default] version 0.17.0
[1] 2020/09/10 05:20:53.670938 [INF] STREAM: ServerID: cCOSlkGXEoGaiviuKe0hkK
[1] 2020/09/10 05:20:53.670944 [INF] STREAM: Go version: go1.13.7
[1] 2020/09/10 05:20:53.670949 [INF] STREAM: Git commit: [f4b7190]
[1] 2020/09/10 05:20:53.673490 [INF] Starting nats-server version 2.1.4
[1] 2020/09/10 05:20:53.673507 [INF] Git commit [fb009af]
[1] 2020/09/10 05:20:53.673817 [INF] Starting http monitor on 0.0.0.0:8222
[1] 2020/09/10 05:20:53.673911 [INF] Listening for client connections on 0.0.0.0:4222
[1] 2020/09/10 05:20:53.673918 [INF] Server id is NCF2SJUFN6EPFVMM6L5IABMG6DFC3C4WVP6OOVVP2HHYI4DUNUJ7MLKD
[1] 2020/09/10 05:20:53.673922 [INF] Server is ready
[1] 2020/09/10 05:20:53.674295 [INF] Listening for route connections on 0.0.0.0:6222
[1] 2020/09/10 05:20:53.690516 [INF] 10.161.13.252:6222 - rid:1 - Route connection created
[1] 2020/09/10 05:20:53.709709 [INF] STREAM: Recovering the state...
[1] 2020/09/10 05:20:53.709952 [INF] STREAM: No recovered state
[1] 2020/09/10 05:20:53.716009 [INF] STREAM: Cluster Node ID : eventbus-default-stan-2
[1] 2020/09/10 05:20:53.716029 [INF] STREAM: Cluster Log Path: /data/stan/logs
[1] 2020/09/10 05:20:53.741975 [INF] STREAM: Message store is RAFT_FILE
[1] 2020/09/10 05:20:53.741989 [INF] STREAM: Store location: /data/stan/store
[1] 2020/09/10 05:20:53.742031 [INF] STREAM: ---------- Store Limits ----------
[1] 2020/09/10 05:20:53.742037 [INF] STREAM: Channels:                  100 *
[1] 2020/09/10 05:20:53.742041 [INF] STREAM: --------- Channels Limits --------
[1] 2020/09/10 05:20:53.742044 [INF] STREAM:   Subscriptions:          1000 *
[1] 2020/09/10 05:20:53.742048 [INF] STREAM:   Messages     :       1000000 *
[1] 2020/09/10 05:20:53.742051 [INF] STREAM:   Bytes        :     976.56 MB *
[1] 2020/09/10 05:20:53.742055 [INF] STREAM:   Age          :       72h0m0s
[1] 2020/09/10 05:20:53.742058 [INF] STREAM:   Inactivity   :     unlimited *
[1] 2020/09/10 05:20:53.742061 [INF] STREAM: ----------------------------------
[1] 2020/09/10 05:21:02.232241 [INF] 10.161.13.15:6222 - rid:9 - Route connection created
[1] 2020/09/10 05:21:02.835225 [INF] STREAM: server became leader, performing leader promotion actions
[1] 2020/09/10 05:21:02.861199 [INF] STREAM: finished leader promotion actions
[1] 2020/09/10 05:21:02.861410 [INF] STREAM: Streaming Server is ready
[1] 2020/09/10 05:21:06.193299 [INF] STREAM: Channel "eventbus-argo" has been created
[1] 2020/09/10 05:21:13.314947 [INF] STREAM: server lost leadership, performing leader stepdown actions
[1] 2020/09/10 05:21:13.315001 [INF] STREAM: finished leader stepdown actions
[1] 2020/09/10 05:21:16.369846 [INF] 10.161.13.252:6222 - rid:1 - Router connection closed
[1] 2020/09/10 05:21:17.514860 [INF] 10.161.12.205:6222 - rid:12 - Route connection created
[1] 2020/09/10 05:21:17.515020 [INF] 10.161.12.205:58888 - rid:13 - Route connection created
[1] 2020/09/10 05:21:17.515237 [INF] 10.161.12.205:58888 - rid:13 - Router connection closed
[1] 2020/09/10 05:21:17.515369 [INF] 10.161.12.205:6222 - rid:12 - Router connection closed
[1] 2020/09/10 05:21:46.691917 [WRN] 127.0.0.1:52198 - cid:5 - Readloop processing time: 6.355763643s
[1] 2020/09/10 05:22:35.653447 [INF] 10.161.13.15:6222 - rid:9 - Router connection closed
```


Eventbus resource:
```
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
spec:
  nats:
    native:
      replicas: 3
      auth: token
      tolerations:
      - key: pooltype
        value: "lowpri"
        operator: "Equal"
        effect: "NoSchedule"
      nodeSelector:
        agentpool: imcopoollowp
```

**Comment by ptemmer** [comment] 2020-09-10 07:41
Might be worth noting that this issue comes up everytime we scale up our Kubernetes cluster nodes again, after scaling them down to zero (to save pennies over night). Deployments / statefulsets are not recreated every time, they are in "Pending" state during the time our cluster is scaled down to zero. Once we start scaling it up again, pods start to deploy.

**Comment by whynowy** [comment] 2020-09-10 17:19
@ptemmer - were your sensor and eventsource pod in "crashloopbackoff" state?

NATS cluster needs at least 2 nodes in place to make it work. According to the logs you posted, it took 4 mins to get 2 PODs up running, and apparently during that time, sensor and eventsource pods could not connect to it. Please note both sensor and eventsource service have similar process to below:

1. When the service starts, it tries to connect to eventbus (sensor has maximum 10 times retry, eventsource does not retry), if it fails, the POD goes to `crashloopbackoff` state, and leverages the ability of k8s to restart the pod;

2. If it goes through the starting stage, there is a reconnection daemon running there to keep reconnecting if the connect is lost.

So I think for your case, since it's been 4 mins passed, eventsource and sensor PODs might have tried several times of restart, and the retry interval was increased. You might can observe longer to see if they will come back.

I don't know if there's anything we can do for your case, a suggestion from me is, you probably can manage a separate nats streaming server somewhere else and keep it running (or start it first before scaling up nodes), and use `exotic` nats eventbus.

**Comment by ptemmer** [comment] 2020-09-10 20:40
Thanks @whynowy for your feedback.
Pod pods were indeed in crashloopbackoff. But that just means that the pod gets restarted forever, with incremental intervals (max 5min) in between each attempt. When I checked this morning, the NATS server had been up and running for over an hour, and the eventsource pod for example had been restarted 30-ish times.

I even tried killing the pod myself, to no avail, same error always "Connect request timeout (possibly wrong cluster ID?)".

I have the feeling the problem lies somewhere else.

**Comment by whynowy** [comment] 2020-09-10 23:40
@ptemmer - then it should be something wrong with the nats streaming cluster, I see leader step down but don't see leadership promotion after that in all the 3 PODs logs, however, based on my rough nats streaming knowledge, I don't know why. 

We really don't recommend you to scale down/up the eventbus pods everyday but keep them running stably. Also, I'm not sure if you are using persistence volumes for them, if not, that means every time when the pods are gone all the data is gone.

**Comment by ptemmer** [comment] 2020-09-11 00:00
Ok, thanks again. I'll dig a bit deeper into the NATS server.
As for the data that we'd loose. What would actually be persisted over there?

**Comment by whynowy** [comment] 2020-12-26 07:33
I assume there's no issue any more, please reopen it or create a new one if you still see a problem.

**Closed by whynowy** 2020-12-26 07:33 UTC
Labels: bug
