### ISSUE TITLE
Duplicate workflows triggered on calendar schedule

### ISSUE THREAD

**Issue by jfouchard** [argoproj/argo-events#202] opened 2019-03-05 18:11 UTC
**Describe the bug**
When using a schedule it seems like two instances are triggered every time.  The calendar-gateway logs show two events being fired: 
```
2019-03-05T18:07:59Z | info  | msg: expected next calendar event |  event-source-name:test2
2019-03-05T18:07:59Z | info  | msg: new event received, dispatching to gateway client |  event-source-name:test2
2019-03-05T18:08:00Z | info  | msg: expected next calendar event |  event-source-name:test2
2019-03-05T18:08:00Z | info  | msg: new event received, dispatching to gateway client |  event-source-name:test2
```

Interval events do not appear to have this issue. 

**To Reproduce**
My Spec:
```
    spec:
      containers:
      - command:
        - /bin/gateway-client
        env:
        - name: GATEWAY_NAMESPACE
          value: argo-events
        - name: GATEWAY_EVENT_SOURCE_CONFIG_MAP
          value: argo-events-config-calendar-gateway-auto
        - name: GATEWAY_NAME
          value: argo-events-config-calendar-gateway-auto
        - name: GATEWAY_CONTROLLER_INSTANCE_ID
          value: argo-events
        - name: GATEWAY_CONTROLLER_NAME
          value: gateway-controller
        - name: GATEWAY_SERVER_PORT
          value: "9330"
        image: argoproj/gateway-client
        imagePullPolicy: Always
        name: gateway-client
        resources: {}
      - command:
        - /bin/calendar-gateway
        env:
        - name: GATEWAY_NAMESPACE
          value: argo-events
        - name: GATEWAY_EVENT_SOURCE_CONFIG_MAP
          value: argo-events-config-calendar-gateway-auto
        - name: GATEWAY_NAME
          value: argo-events-config-calendar-gateway-auto
        - name: GATEWAY_CONTROLLER_INSTANCE_ID
          value: argo-events
        - name: GATEWAY_CONTROLLER_NAME
          value: gateway-controller
        - name: GATEWAY_SERVER_PORT
          value: "9330"
        image: argoproj/calendar-gateway
        imagePullPolicy: Always
        name: calendar-events
        resources: {}
      serviceAccountName: argo-events-sa
```

And the configMap:
```
data:
  test2: 'schedule: 08 * * * *'
```
**Expected behavior**
A single event to be fired.

**Screenshots**

**Environment (please complete the following information):**
 Argo deployed via helmfiles @ latest.

Note, I'm pretty new to Argo, so this could certainly be a config issue - I just don't see where at all.

**Comment by VaibhavPage** [comment] 2019-03-05 20:10
Ran the gateway with the same schedule as yours but couldn't reproduce the behavior you saw. It always triggers single pod.

**Comment by VaibhavPage** [comment] 2019-03-05 20:19
Can you post the output of `kubectl describe configmap <your-calendar-gateway-configmap>` and `kubectl describe gateway <your-calendar-gateway>`

**Comment by jfouchard** [comment] 2019-03-05 20:29
Of course:
`configMap`:
```
Name:         argo-events-config-calendar-gateway-auto
Namespace:    argo-events
Labels:       app.kubernetes.io/instance=argo-events-config
              app.kubernetes.io/managed-by=Tiller
              app.kubernetes.io/name=argo-events-config
              helm.sh/chart=argo-events-config-0.1.0
Annotations:  <none>

Data
====
test2:
----
schedule: 26 * * * *
Events:  <none>
```

`Gateway`:
```
Name:         argo-events-config-webhook-gateway-auto
Namespace:    argo-events
Labels:       app.kubernetes.io/instance=argo-events-config
              app.kubernetes.io/managed-by=Tiller
              app.kubernetes.io/name=argo-events-config
              gateway-name=argo-events-config-webhook-gateway-auto
              gateways.argoproj.io/gateway-controller-instanceid=argo-events
              helm.sh/chart=argo-events-config-0.1.0
              sensors.argoproj.io/phase=Running
Annotations:  gateways.argoproj.io/phase=Running
API Version:  argoproj.io/v1alpha1
Kind:         Gateway
Metadata:
  Cluster Name:
  Creation Timestamp:  2019-03-05T18:27:10Z
  Generation:          1
  Resource Version:    1286263
  Self Link:           /apis/argoproj.io/v1alpha1/namespaces/argo-events/gateways/argo-events-config-webhook-gateway-auto
  UID:                 4a30962c-3f74-11e9-aa11-025000000001
Spec:
  Config Map:  argo-events-config-webhook-gateway-auto
  Deploy Spec:
    Metadata:
      Creation Timestamp:  <nil>
      Labels:
        Gateway - Name:  argo-events-config-webhook-gateway-auto
      Name:              argo-events-config-webhook-gateway-auto
      Owner References:
        API Version:           argoproj.io/v1alpha1
        Block Owner Deletion:  true
        Controller:            true
        Kind:                  Gateway
        Name:                  argo-events-config-webhook-gateway-auto
        UID:                   4a30962c-3f74-11e9-aa11-025000000001
    Spec:
      Containers:
        Command:
          /bin/gateway-client
        Env:
          Name:             GATEWAY_NAMESPACE
          Value:            argo-events
          Name:             GATEWAY_EVENT_SOURCE_CONFIG_MAP
          Value:            argo-events-config-webhook-gateway-auto
          Name:             GATEWAY_NAME
          Value:            argo-events-config-webhook-gateway-auto
          Name:             GATEWAY_CONTROLLER_INSTANCE_ID
          Value:            argo-events
          Name:             GATEWAY_CONTROLLER_NAME
          Value:            gateway-controller
          Name:             GATEWAY_SERVER_PORT
          Value:            9330
        Image:              argoproj/gateway-client
        Image Pull Policy:  Always
        Name:               gateway-client
        Resources:
        Command:
          /bin/webhook-gateway
        Env:
          Name:             GATEWAY_NAMESPACE
          Value:            argo-events
          Name:             GATEWAY_EVENT_SOURCE_CONFIG_MAP
          Value:            argo-events-config-webhook-gateway-auto
          Name:             GATEWAY_NAME
          Value:            argo-events-config-webhook-gateway-auto
          Name:             GATEWAY_CONTROLLER_INSTANCE_ID
          Value:            argo-events
          Name:             GATEWAY_CONTROLLER_NAME
          Value:            gateway-controller
          Name:             GATEWAY_SERVER_PORT
          Value:            9330
        Image:              argoproj/webhook-gateway
        Image Pull Policy:  Always
        Name:               webhook-events
        Resources:
      Service Account Name:  argo-events-sa
    Status:
  Event Protocol:
    Http:
      Port:  9300
    Nats:
      Type:
      URL:
    Type:          HTTP
  Event Version:   1.0
  Processor Port:  9330
  Service Spec:
    Metadata:
      Creation Timestamp:  <nil>
      Name:                argo-events-config-webhook-gateway
      Owner References:
        API Version:           argoproj.io/v1alpha1
        Block Owner Deletion:  true
        Controller:            true
        Kind:                  Gateway
        Name:                  argo-events-config-webhook-gateway-auto
        UID:                   4a30962c-3f74-11e9-aa11-025000000001
    Spec:
      Ports:
        Port:         12000
        Target Port:  12000
      Selector:
        Gateway - Name:  argo-events-config-webhook-gateway-auto
      Type:              LoadBalancer
    Status:
      Load Balancer:
  Type:  webhook
  Watchers:
Status:
  Message:  gateway is active
  Nodes:
    1996546312:
      Display Name:  hooktest2
      Id:            1996546312
      Message:       event_source_is_running
      Name:          hooktest2
      Phase:         Running
      Started At:    2019-03-05T19:22:10.072710Z
      Update Time:   <nil>
  Phase:             Running
  Started At:        2019-03-05T18:27:10Z
Events:              <none>
```

**Comment by VaibhavPage** [comment] 2019-03-06 12:51
I don't see any issue with the gateway or gateway-configmap and I am not able to reproduce the issue. Can you delete the current installation of gateway, configmap, and sensor, and re-install?

**Comment by jfouchard** [comment] 2019-03-06 20:16
Some more details:

Using Docker for Mac (v. 2.0.0.3, Kubernetes v1.10.11)
- I had the same results after deleting and re-creating all of Argo, Argo-Events, all gateways and sensors
- I had the same results doing the above with either the helm-charts or the manifests in the `argo-events` readme
- The issue persisted with the `v0.7` image of the `calendar-scheduler` (instead of `latest`/`v0.8`)
- The issue persisted with the example gateway & configmap in this repo
- The same issue occurred on a different Mac

We were unable to reproduce this far however in our EKS cluster.

**Comment by tunaaksoy** [comment] 2019-03-14 11:24
I had this issue as well but it was intermittent and I was not able to reproduce it reliably.

**Comment by VaibhavPage** [comment] 2019-03-26 19:26
Do you still face this issue with v0.8.3? If not, can we close this issue?

**Comment by tunaaksoy** [comment] 2019-03-27 09:27
The issue still exists in v0.8.3.

**Comment by VaibhavPage** [comment] 2019-06-17 23:12
Closing for now. Let me know if you still this in v0.9.2

**Closed by VaibhavPage** 2019-06-17 23:12 UTC

**Comment by donaldrauscher** [comment] 2019-07-02 12:34
I am having this issue with v0.9.2
