### ISSUE TITLE
Errors when trying to update gateway deployment definition

### ISSUE THREAD

**Issue by sudermanjr** [argoproj/argo-events#612] opened 2020-04-23 16:07 UTC
**Describe the bug**
When I update a gateway definition and deploy it, I get these errors in the controller logs, and the deployment is not updated.

```
argo-events-kepler-prod-gateway-controller-7dfdddf96b-qpmhq gateway-controller ERRO[2020-04-23 15:51:45] gateway is in error state. checking updates for gateway object...
argo-events-kepler-prod-gateway-controller-7dfdddf96b-qpmhq gateway-controller ERRO[2020-04-23 15:51:45] failed to update resources for the gateway    error="deployment metadata is expected to be set in gateway object"
argo-events-kepler-prod-gateway-controller-7dfdddf96b-qpmhq gateway-controller ERRO[2020-04-23 15:51:45] failed to operate on the gateway object       error="deployment metadata is expected to be set in gateway object" gateway=kepler-webhook-gateway
argo-events-kepler-prod-gateway-controller-7dfdddf96b-qpmhq gateway-controller ERRO[2020-04-23 15:51:45] controller failed to handle error             error="exceeded max requeues"
```

**To Reproduce**
1. Deploy a basic gateway such as the one here https://github.com/argoproj/argo-events/blob/master/examples/gateways/webhook.yaml#L12
2. Modify that gateway by adding something to the pod spec. In my case I added resource limits and requests to the containers
3. Apply the gateway yaml using `kubectl apply -f <file>`
4. Watch the controller logs
5. Verify that the deployment for the gateway does not have the changes requested, and the gateway pod has not been re-deployed

**Expected behavior**
The deployment should have been modified, triggering a rollout of the pods

**Environment (please complete the following information):**
 Argo-events v0.13.0
Kubernetes 1.15.0

**Additional context**
I am going to try updating to v0.14.0. I don't see anything that indicates a change that would fix it, but I should update anyway.

**Comment by sudermanjr** [comment] 2020-04-23 16:16
Update: Still seem to have this issue in 0.14

**Comment by VaibhavPage** [comment] 2020-04-24 15:16
@whynowy ^, if there is an issue, we can put a fix as a part of your PR.

**Comment by whynowy** [comment] 2020-04-24 15:56
> @whynowy ^, if there is an issue, we can put a fix as a part of your PR.

👍

**Comment by whynowy** [comment] 2020-04-24 20:57
@sudermanjr - I wasn't able to reproduce the issue you mentioned, I did see the gateway status is Error one time , but that was because I was too fast to recreate the Gateway after I deleted it - the LB service hadn't been deleted before it was recreated, this is reasonable. 

Could you post the error you see in the log? Also you can post your `Gateway` object status by running `kubectl get gateway webhook-gateway -ojson | jq '.status'`.

**Comment by sudermanjr** [comment] 2020-04-25 00:00
I can post the gateway status on Monday. The log messages are on my original report

**Comment by whynowy** [comment] 2020-04-25 21:24
@sudermanjr - thanks, I missed the log above, will look into it.

**Comment by sudermanjr** [comment] 2020-04-27 16:27
Here's the gateway status when I look at the gateway in-cluster:

```
message: deployments.apps "webhook-gateway-http" already exists
phase: Error
resources:
  deployment: null
startedAt: "2020-04-21T23:46:38Z"
```

**Comment by iMoses** [comment] 2020-06-21 02:48
I'm having the same issue on both 0.14 and 0.16, any hints on how to debug it?

**Comment by whynowy** [comment] 2020-06-21 04:02
Hi @iMoses - this is a bug, to bypass this, you have to recreate the gateway. I'll fix this.

**Comment by whynowy** [comment] 2020-07-15 17:54
Not an issue any more with merged Gateway and EventSource

**Closed** 2020-07-15 18:44 UTC
Labels: bug
