### ISSUE TITLE
triggers.template.when.any not loop all list

### ISSUE THREAD

**Issue by Erik-Securenative** [argoproj/argo-events#297] opened 2019-06-16 12:17 UTC
**Describe the bug**
when i try to set the sensor with triggers.template.when.any: ["a", "b"] only "a" event get triggered and "b" event not. but if i will change the order triggers.template.when.any: ["b", "a"] "b" event will get triggered and "a" will not. looks like the loop is broken?

**To Reproduce**
1. setup https://github.com/argoproj/argo-events/blob/master/examples/sensors/dependencies-circuit-complex.yaml
2. trigger group_2

**Comment by VaibhavPage** [comment] 2019-06-17 23:08
Can you post your sensor resource file? For me, `any` condition works as expected.

**Comment by Erik-Securenative** [comment] 2019-06-20 06:40
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-sensor
  labels:
    # sensor controller with instanceId "argo-events" will process this sensor
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
    # sensor controller will use this label to match with it's own version
    # do not remove
    argo-events-sensor-version: v0.10
spec:
  template:
    spec:
      containers:
        - name: "sensor"
          image: "argoproj/sensor"
          imagePullPolicy: Always
      serviceAccountName: argo-events-sa
  dependencies:
    - name: "github-gateway:GeoLocation-push-stg"
      filters:
        name: "data-filter"
        data:
          - path: "ref"
            type: string
            value:
              - "refs/heads/fr-stg"
    - name: "github-gateway:GeoLocation-push-prod"
      filters:
        name: "data-filter"
        data:
          - path: "ref"
            type: string
            value:
              - "refs/heads/nv-prod"
    - name: "github-gateway:FlowManager-push-stg"
      filters:
        name: "data-filter"
        data:
          - path: "ref"
            type: string
            value:
              - "refs/heads/fr-stg"
    - name: "github-gateway:FlowManager-push-prod"
      filters:
        name: "data-filter"
        data:
          - path: "ref"
            type: string
            value:
              - "refs/heads/nv-prod"
    - name: "github-gateway:AccounCompromised-push-stg"
      filters:
        name: "data-filter"
        data:
          - path: "ref"
            type: string
            value:
              - "refs/heads/fr-stg"
    - name: "github-gateway:AccounCompromised-push-prod"
      filters:
        name: "data-filter"
        data:
          - path: "ref"
            type: string
            value:
              - "refs/heads/nv-prod"
    - name: "github-gateway:Alerting-push-stg"
      filters:
        name: "data-filter"
        data:
          - path: "ref"
            type: string
            value:
              - "refs/heads/fr-stg"
    - name: "github-gateway:Alerting-push-prod"
      filters:
        name: "data-filter"
        data:
          - path: "ref"
            type: string
            value:
              - "refs/heads/nv-prod"
  dependencyGroups:
    - name: "GeoLocationpushstg"
      dependencies:
        - "github-gateway:GeoLocation-push-stg"
    - name: "GeoLocationpushprod"
      dependencies:
        - "github-gateway:GeoLocation-push-prod"
    - name: "FlowManagerpushstg"
      dependencies:
        - "github-gateway:FlowManager-push-stg"
    - name: "FlowManagerpushprod"
      dependencies:
        - "github-gateway:FlowManager-push-prod"
    - name: "AccounCompromisedpushstg"
      dependencies:
        - "github-gateway:AccounCompromised-push-stg"
    - name: "AccounCompromisedpushprod"
      dependencies:
        - "github-gateway:AccounCompromised-push-prod"
    - name: "Alertingpushstg"
      dependencies:
        - "github-gateway:Alerting-push-stg"
    - name: "Alertingpushprod"
      dependencies:
        - "github-gateway:Alerting-push-prod"
  circuit: "GeoLocationpushstg || GeoLocationpushprod || FlowManagerpushstg || FlowManagerpushprod || AccounCompromisedpushstg || AccounCompromisedpushprod || Alertingpushstg || Alertingpushprod"
  eventProtocol:
    type: "HTTP"
    http:
      port: "9300"
  triggers:
    - template:
        when:
          any:
            - "AccounCompromisedpushstg"
            - "GeoLocation-push-stg"
        name: github-workflow-trigger-push
        group: argoproj.io
        version: v1alpha1
        kind: Workflow
        source:
          configmap:
            name: workflow-github
            namespace: argo-events
            key: wfpush
      resourceParameters:
        - src:
            event: "github-gateway:GeoLocation-push-stg"
            path: "ref"
            value: "n"
          dest: spec.arguments.parameters.0.value
        - src:
            event: "github-gateway:GeoLocation-push-stg"
            path: "repository.ssh_url"
            value: "n"
          dest: spec.arguments.parameters.1.value
        - src:
            event: "github-gateway:GeoLocation-push-stg"
            path: "head_commit.message"
            value: "n"
          dest: spec.arguments.parameters.2.value
        - src:
            event: "github-gateway:GeoLocation-push-stg"
            path: "repository.name"
            value: "n"
          dest: spec.arguments.parameters.3.value
        - src:
            event: "github-gateway:GeoLocation-push-stg"
            path: "head_commit.id"
            value: "n"
          dest: spec.arguments.parameters.4.value
        - src:
            event: "github-gateway:AccounCompromised-push-stg"
            path: "ref"
            value: "n"
          dest: spec.arguments.parameters.0.value
        - src:
            event: "github-gateway:AccounCompromised-push-stg"
            path: "repository.ssh_url"
            value: "n"
          dest: spec.arguments.parameters.1.value
        - src:
            event: "github-gateway:AccounCompromised-push-stg"
            path: "head_commit.message"
            value: "n"
          dest: spec.arguments.parameters.2.value
        - src:
            event: "github-gateway:AccounCompromised-push-stg"
            path: "repository.name"
            value: "n"
          dest: spec.arguments.parameters.3.value
        - src:
            event: "github-gateway:AccounCompromised-push-stg"
            path: "head_commit.id"
            value: "n"
          dest: spec.arguments.parameters.4.value
    - template:
        when:
          any:
            - "AccounCompromisedpushprod"
            - "GeoLocationpushprod"
        name: github-workflow-trigger-push
        group: argoproj.io
        version: v1alpha1
        kind: Workflow
        source:
          configmap:
            name: workflow-github-push-prod
            namespace: argo-events
            key: wfpushprod
      resourceParameters:
        - src:
            event: "github-gateway:GeoLocation-push-prod"
            path: "ref"
            value: "n"
          dest: spec.arguments.parameters.0.value
        - src:
            event: "github-gateway:GeoLocation-push-prod"
            path: "repository.ssh_url"
            value: "n"
          dest: spec.arguments.parameters.1.value
        - src:
            event: "github-gateway:GeoLocation-push-prod"
            path: "head_commit.message"
            value: "n"
          dest: spec.arguments.parameters.2.value
        - src:
            event: "github-gateway:GeoLocation-push-prod"
            path: "repository.name"
            value: "n"
          dest: spec.arguments.parameters.3.value
        - src:
            event: "github-gateway:GeoLocation-push-prod"
            path: "head_commit.id"
            value: "n"
          dest: spec.arguments.parameters.4.value
        - src:
            event: "github-gateway:AccounCompromised-push-prod"
            path: "ref"
            value: "n"
          dest: spec.arguments.parameters.0.value
        - src:
            event: "github-gateway:AccounCompromised-push-prod"
            path: "repository.ssh_url"
            value: "n"
          dest: spec.arguments.parameters.1.value
        - src:
            event: "github-gateway:AccounCompromised-push-prod"
            path: "head_commit.message"
            value: "n"
          dest: spec.arguments.parameters.2.value
        - src:
            event: "github-gateway:AccounCompromised-push-prod"
            path: "repository.name"
            value: "n"
          dest: spec.arguments.parameters.3.value
        - src:
            event: "github-gateway:AccounCompromised-push-prod"
            path: "head_commit.id"
            value: "n"
          dest: spec.arguments.parameters.4.value
    - template:
        when:
          all:
            - "FlowManagerpushstg"
        name: github-workflow-trigger-push-multi
        group: argoproj.io
        version: v1alpha1
        kind: Workflow
        source:
          configmap:
            name: workflow-github-push-multi
            namespace: argo-events
            key: wfpushmulti
      resourceParameters:
        - src:
            event: "github-gateway:FlowManager-push-multi-stg"
            path: "ref"
            value: "n"
          dest: spec.arguments.parameters.0.value
        - src:
            event: "github-gateway:FlowManager-push-multi-stg"
            path: "repository.ssh_url"
            value: "n"
          dest: spec.arguments.parameters.1.value
        - src:
            event: "github-gateway:FlowManager-push-multi-stg"
            path: "head_commit.message"
            value: "n"
          dest: spec.arguments.parameters.2.value
        - src:
            event: "github-gateway:FlowManager-push-multi-stg"
            path: "repository.name"
            value: "n"
          dest: spec.arguments.parameters.3.value
        - src:
            event: "github-gateway:FlowManager-push-multi-stg"
            path: "head_commit.id"
            value: "n"
          dest: spec.arguments.parameters.4.value
    - template:
        when:
          any:
            - "Alertingpushprod"
            - "FlowManagerpushprod"
        name: github-workflow-trigger-push-multi
        group: argoproj.io
        version: v1alpha1
        kind: Workflow
        source:
          configmap:
            name: workflow-github-push-multi-prod
            namespace: argo-events
            key: wfpushmulti-prod
      resourceParameters:
        - src:
            event: "github-gateway:Alerting-push-prod"
            path: "ref"
            value: "n"
          dest: spec.arguments.parameters.0.value
        - src:
            event: "github-gateway:Alerting-push-prod"
            path: "repository.ssh_url"
            value: "n"
          dest: spec.arguments.parameters.1.value
        - src:
            event: "github-gateway:Alerting-push-prod"
            path: "head_commit.message"
            value: "n"
          dest: spec.arguments.parameters.2.value
        - src:
            event: "github-gateway:Alerting-push-prod"
            path: "repository.name"
            value: "n"
          dest: spec.arguments.parameters.3.value
        - src:
            event: "github-gateway:Alerting-push-prod"
            path: "head_commit.id"
            value: "n"
          dest: spec.arguments.parameters.4.value
        - src:
            event: "github-gateway:Alerting-push-prod"
            path: "ref"
            value: "n"
          dest: spec.arguments.parameters.0.value
        - src:
            event: "github-gateway:Alerting-push-prod"
            path: "repository.ssh_url"
            value: "n"
          dest: spec.arguments.parameters.1.value
        - src:
            event: "github-gateway:Alerting-push-prod"
            path: "head_commit.message"
            value: "n"
          dest: spec.arguments.parameters.2.value
        - src:
            event: "github-gateway:Alerting-push-prod"
            path: "repository.name"
            value: "n"
          dest: spec.arguments.parameters.3.value
        - src:
            event: "github-gateway:Alerting-push-prod"
            path: "head_commit.id"
            value: "n"
          dest: spec.arguments.parameters.4.value

**Comment by VaibhavPage** [comment] 2019-06-20 11:40
Thanks for posting the spec. I'll take a look

**Comment by ldrygala** [comment] 2019-08-05 14:07
i had same problem. I think the problem is here https://github.com/argoproj/argo-events/blob/f02d2cd7bdac456bb8ba6b3de4a97831c403c7af/sensors/trigger.go#L86, i'm not a go expert but i think `return false` should be one line below

**Comment by VaibhavPage** [comment] 2019-08-05 23:42
😅 @ldrygala you are right . I’ll put the fix asap

**Comment by VaibhavPage** [comment] 2019-08-06 01:08
#327

**Comment by VaibhavPage** [comment] 2019-10-05 20:28
fixed in v0.10

**Closed by VaibhavPage** 2019-10-05 20:28 UTC
Labels: testing
