### ISSUE TITLE
In case gcp pubsub eventsource, sensor workflow was duplicately created when pubsub message came.

### ISSUE THREAD

**Issue by duluong** [argoproj/argo-events#929] opened 2020-10-27 06:16 UTC
**Describe the bug**
I need a job run when got message from gcp pubsub.
So I've created a eventsource and sensor to handle it.
The trigger ran well and made the right workflow.
But the workflow was alway duplicately created.

**To Reproduce**
My yamls as bellow.

eventsource-gcp-pubsub.yaml
```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: gcp-pubsub-argo-test
spec:
  pubSub:
    decode-data:
      jsonBody: true
      projectID: abc-xyz
      subscriptionID: abc-xyz-topic-sub
      credentialSecret:
        name: service-account-abc-xyz
        key: service-account-abc-xyz.json
```

sensor-job.yaml
```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: rawdataprocess-job
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: rawdataprocess-job-dep
      eventSourceName: gcp-pubsub-argo-test
      eventName: decode-data
  triggers:
    - template:
        name: rawdataprocess-job-workflow-trigger
        k8s:
          namespace: aaa-xxxx
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                namespace: grdsys-dev
                generateName: rawdataprocess-job-
              spec:
                entrypoint: rawdataprocess-job
                arguments:
                  parameters:
                    - name: bucketId
                      value: ""
                    - name: objectId
                      value: ""
                templates:
                  - name: rawdataprocess-job
                    inputs:
                      parameters:
                        - name: bucketId
                        - name: objectId
                    container:
                      image: asia.gcr.io/abc-xyz/data-process:argo
                      command: ["sh", "-c"]
                      args:
                      - |
                        /app/rawdataprocess --bucket-id "{{inputs.parameters.bucketId}}" --object-id "{{inputs.parameters.objectId}}"
          parameters:
          - src:
              dependencyName: rawdataprocess-job-dep
              dataKey: attributes.bucketId
            dest: spec.arguments.parameters.0.value
          - src:
              dependencyName: rawdataprocess-job-dep
              dataKey: attributes.objectId
            dest: spec.arguments.parameters.1.value
```

**Screenshots**
wf job was duplicated
<img width="769" alt="Screen Shot 2020-10-27 at 15 14 30" src="https://user-images.githubusercontent.com/6425063/97264521-78f63980-1868-11eb-9c0f-110cfdf8a12e.png">

**Environment (please complete the following information):**
 - Kubernetes: [v1.18.9]
 - Argo: [v2.11.6]
 - Argo Events: [v1.0.0]

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment] 2020-10-27 07:11
@duluong - could you post sensor POD log?

**Comment by duluong** [comment] 2020-10-27 08:10
@whynowy 
thanks for your response.
here is sensor pod log

```
{"level":"info","ts":1603691416.6019216,"logger":"argo-events.sensor","caller":"sensors/listener.go:349","msg":"Dependency expression for trigger rawdataprocess-job-workflow-trigger before simlification: rawdataprocess-job-dep","sensorName":"rawdataprocess-job"}
{"level":"info","ts":1603691416.6027005,"logger":"argo-events.sensor","caller":"sensors/listener.go:356","msg":"Dependency expression for trigger rawdataprocess-job-workflow-trigger after simlification: rawdataprocess-job-dep","sensorName":"rawdataprocess-job"}
{"level":"info","ts":1603691416.6028464,"logger":"argo-events.sensor","caller":"sensors/listener.go:212","msg":"Sensor started.","sensorName":"rawdataprocess-job"}
{"level":"info","ts":1603691416.6055903,"logger":"argo-events.sensor","caller":"driver/nats.go:92","msg":"NATS auth strategy: Token","sensorName":"rawdataprocess-job","clientID":"client-2365991510"}
{"level":"info","ts":1603691416.613638,"logger":"argo-events.sensor","caller":"driver/nats.go:104","msg":"Connected to NATS server.","sensorName":"rawdataprocess-job","clientID":"client-2365991510"}
{"level":"info","ts":1603691416.6173694,"logger":"argo-events.sensor","caller":"driver/nats.go:117","msg":"Connected to NATS streaming server.","sensorName":"rawdataprocess-job","clientID":"client-2365991510"}
{"level":"info","ts":1603691416.6174362,"logger":"argo-events.sensor","caller":"sensors/listener.go:178","msg":"starting eventbus connection daemon for client client-2365991510...","sensorName":"rawdataprocess-job"}
{"level":"info","ts":1603691416.617568,"logger":"argo-events.sensor","caller":"sensors/listener.go:166","msg":"started subscribing to events for triggers [rawdataprocess-job-workflow-trigger] with client client-2365991510","sensorName":"rawdataprocess-job"}
{"level":"info","ts":1603691416.6197221,"logger":"argo-events.sensor","caller":"driver/nats.go:156","msg":"Subscribed to subject eventbus-argo-events ...","sensorName":"rawdataprocess-job","clientID":"client-2365991510"}
{"level":"info","ts":1603692925.8464277,"logger":"argo-events.sensor","caller":"standard-k8s/standar-k8s.go:163","msg":"creating the object...","sensorName":"rawdataprocess-job"}
{"level":"info","ts":1603692925.8691645,"logger":"argo-events.sensor","caller":"sensors/listener.go:266","msg":"successfully processed the trigger","sensorName":"rawdataprocess-job","triggerName":"rawdataprocess-job-workflow-trigger"}
{"level":"info","ts":1603692926.1419728,"logger":"argo-events.sensor","caller":"standard-k8s/standar-k8s.go:163","msg":"creating the object...","sensorName":"rawdataprocess-job"}
{"level":"info","ts":1603692926.154107,"logger":"argo-events.sensor","caller":"sensors/listener.go:266","msg":"successfully processed the trigger","sensorName":"rawdataprocess-job","triggerName":"rawdataprocess-job-workflow-trigger"}
```

**Comment by whynowy** [comment] 2020-10-27 08:26
@duluong  - Are you able to reproduce it? Just want to make sure if it's a random issue, or it consistently happens. If it's a random issue, I think it should be caused by NATS `atLeastOnce` delivery guarantee, which sometimes causes duplicate delivery, and this issue has been addressed in https://github.com/argoproj/argo-events/commit/166e36db23ca82e5d28a264e63ef125457a24858, it is not in v1.0.0, but will be in next release.

**Comment by duluong** [comment] 2020-10-27 08:42
@whynowy 
I've tried it several times, but the result did not change.
Even I deleted both argo & argo-events namespace, then recreated from scratch.

**Comment by whynowy** [comment] 2020-10-27 16:30
@duluong - Since you can firmly reproduce it, can you follow the way below to check how many message were sent to EventBus from EventSource POD in that period?

1. Run `kubectl get secret eventbus-default-client -ojsonpath='{.data.client-auth}' | base64 --decode | awk -F\" '{print $2}'`, you will get the token to access EventBus.

2. Start a `nats-box` pod for debugging

```
kubectl run -i --rm --tty nats-box --image=synadia/nats-box --restart=Never
```
3. Within the `nats-box` POD, replace `{TOKEN}` and `{your-namespace}`, run `/usr/local/bin/stan-sub -s nats://{TOKEN}@eventbus-default-stan-svc:4222 -c eventbus-default eventbus-{your-namespace} -all`

You will get all the messages in the last 72 hours, each of the message looks like below, you can check those metadata (source = `eventSourceName`, subject=`eventName`), or `base64` decode the `data` field for troubleshooting.

```
[#16058] Received: sequence:21464 subject:"eventbus-argo-events" data:"{\"data_base64\":\"eyJldmVudFRpbWUiOiIyMDIwLTA4LTI4IDA0OjM2OjQ0LjAwMDA5MjE1NSArMDAwMCBVVEMgbT0rMzYwOTkuOTc2ODE5NzQzIn0=\",\"datacontenttype\":\"application/json\",\"id\":\"31616664323334302d303264372d343663302d396636662d326234616132383561646536\",\"source\":\"calendar\",\"specversion\":\"1.0\",\"subject\":\"example2\",\"time\":\"2020-08-28T04:36:44.000207112Z\",\"type\":\"calendar\"}" timestamp:1598589404000764639
```

**Comment by duluong** [comment] 2020-10-28 05:13
@whynowy 
I've tried following your instruction. Needed specify namespace in the #1 and #2 .
Yeah, I'm able to get the message trigger from pubsub.
It was duplicated.
I sent only one message into pubsub, but the termial in #3 shown 2 messages with the same source & subject. And the sequence is serial number.

**Comment by whynowy** [comment] 2020-10-28 06:45
Then it's for sure not an issue of Sensor or EventBus. Can you also post the eventsource pod log?

**Comment by duluong** [comment] 2020-10-28 06:53
@whynowy 
sure. here is log for one pubsub message.
```
[#3] Received: sequence:79 subject:"eventbus-argo-events" data:"{\"data_base64\":\"eyJpZCI6IjE2ODQ3NTc1MzQzNjkzNDkiLCJib2R5Ijp7ImtpbmQiOiJzdG9yYWdlI29iamVjdCIsImlkIjoieGJhbmRfcGFja2V0X3N0b3JlX2Rldi8yMDIwYXVnL3Rlc3QvNzI3XzVfMjAyMDA5MjQwNDM3MjRfc3RyaXhfMjAyMC1TZXAtMjQtMDQtMzktMDAvMTYwMzg2MTYxMDgzNjk4NiIsInNlbGZMaW5rIjoiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vc3RvcmFnZS92MS9iL3hiYW5kX3BhY2tldF9zdG9yZV9kZXYvby8yMDIwYXVnJTJGdGVzdCUyRjcyN181XzIwMjAwOTI0MDQzNzI0X3N0cml4XzIwMjAtU2VwLTI0LTA0LTM5LTAwIiwibmFtZSI6IjIwMjBhdWcvdGVzdC83MjdfNV8yMDIwMDkyNDA0MzcyNF9zdHJpeF8yMDIwLVNlcC0yNC0wNC0zOS0wMCIsImJ1Y2tldCI6InhiYW5kX3BhY2tldF9zdG9yZV9kZXYiLCJnZW5lcmF0aW9uIjoiMTYwMzg2MTYxMDgzNjk4NiIsIm1ldGFnZW5lcmF0aW9uIjoiMSIsImNvbnRlbnRUeXBlIjoiYXBwbGljYXRpb24vb2N0ZXQtc3RyZWFtIiwidGltZUNyZWF0ZWQiOiIyMDIwLTEwLTI4VDA1OjA2OjUwLjgzNloiLCJ1cGRhdGVkIjoiMjAyMC0xMC0yOFQwNTowNjo1MC44MzZaIiwic3RvcmFnZUNsYXNzIjoiUkVHSU9OQUwiLCJ0aW1lU3RvcmFnZUNsYXNzVXBkYXRlZCI6IjIwMjAtMTAtMjhUMDU6MDY6NTAuODM2WiIsInNpemUiOiI2NDA2MzE5NjgiLCJtZDVIYXNoIjoiaUZzMy95dzFhMmJnODIzQ2c0Zmkrdz09IiwibWVkaWFMaW5rIjoiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vZG93bmxvYWQvc3RvcmFnZS92MS9iL3hiYW5kX3BhY2tldF9zdG9yZV9kZXYvby8yMDIwYXVnJTJGdGVzdCUyRjcyN181XzIwMjAwOTI0MDQzNzI0X3N0cml4XzIwMjAtU2VwLTI0LTA0LTM5LTAwP2dlbmVyYXRpb249MTYwMzg2MTYxMDgzNjk4Nlx1MDAyNmFsdD1tZWRpYSIsImNyYzMyYyI6IkY2M3dOdz09IiwiZXRhZyI6IkNQcm4xSXpDMXV3Q0VBRT0ifSwiYXR0cmlidXRlcyI6eyJidWNrZXRJZCI6InhiYW5kX3BhY2tldF9zdG9yZV9kZXYiLCJldmVudFRpbWUiOiIyMDIwLTEwLTI4VDA1OjA2OjUwLjgzNjY3NFoiLCJldmVudFR5cGUiOiJPQkpFQ1RfRklOQUxJWkUiLCJub3RpZmljYXRpb25Db25maWciOiJwcm9qZWN0cy9fL2J1Y2tldHMveGJhbmRfcGFja2V0X3N0b3JlX2Rldi9ub3RpZmljYXRpb25Db25maWdzLzEiLCJvYmplY3RHZW5lcmF0aW9uIjoiMTYwMzg2MTYxMDgzNjk4NiIsIm9iamVjdElkIjoiMjAyMGF1Zy90ZXN0LzcyN181XzIwMjAwOTI0MDQzNzI0X3N0cml4XzIwMjAtU2VwLTI0LTA0LTM5LTAwIiwicGF5bG9hZEZvcm1hdCI6IkpTT05fQVBJX1YxIn0sInB1Ymxpc2hUaW1lIjoiMjAyMC0xMC0yOCAwNTowNjo1MS4wNjIgKzAwMDAgVVRDIn0=\",\"datacontenttype\":\"application/json\",\"id\":\"63326331373662392d316430642d343436302d616234302d306165656238356564323034\",\"source\":\"gcp-pubsub-argo-test\",\"specversion\":\"1.0\",\"subject\":\"decode-rawdata\",\"time\":\"2020-10-28T05:06:51.113437255Z\",\"type\":\"pubsub\"}" timestamp:1603861611114258214 
[#4] Received: sequence:80 subject:"eventbus-argo-events" data:"{\"data_base64\":\"eyJpZCI6IjE2ODQ3NTg1NzczOTE1NTgiLCJib2R5Ijp7ImtpbmQiOiJzdG9yYWdlI29iamVjdCIsImlkIjoieGJhbmRfcGFja2V0X3N0b3JlX2Rldi8yMDIwYXVnL3Rlc3QvNzI3XzVfMjAyMDA5MjQwNDM3MjRfc3RyaXhfMjAyMC1TZXAtMjQtMDQtMzktMDAvMTYwMzg2MTYxMDgzNjk4NiIsInNlbGZMaW5rIjoiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vc3RvcmFnZS92MS9iL3hiYW5kX3BhY2tldF9zdG9yZV9kZXYvby8yMDIwYXVnJTJGdGVzdCUyRjcyN181XzIwMjAwOTI0MDQzNzI0X3N0cml4XzIwMjAtU2VwLTI0LTA0LTM5LTAwIiwibmFtZSI6IjIwMjBhdWcvdGVzdC83MjdfNV8yMDIwMDkyNDA0MzcyNF9zdHJpeF8yMDIwLVNlcC0yNC0wNC0zOS0wMCIsImJ1Y2tldCI6InhiYW5kX3BhY2tldF9zdG9yZV9kZXYiLCJnZW5lcmF0aW9uIjoiMTYwMzg2MTYxMDgzNjk4NiIsIm1ldGFnZW5lcmF0aW9uIjoiMSIsImNvbnRlbnRUeXBlIjoiYXBwbGljYXRpb24vb2N0ZXQtc3RyZWFtIiwidGltZUNyZWF0ZWQiOiIyMDIwLTEwLTI4VDA1OjA2OjUwLjgzNloiLCJ1cGRhdGVkIjoiMjAyMC0xMC0yOFQwNTowNjo1MC44MzZaIiwic3RvcmFnZUNsYXNzIjoiUkVHSU9OQUwiLCJ0aW1lU3RvcmFnZUNsYXNzVXBkYXRlZCI6IjIwMjAtMTAtMjhUMDU6MDY6NTAuODM2WiIsInNpemUiOiI2NDA2MzE5NjgiLCJtZDVIYXNoIjoiaUZzMy95dzFhMmJnODIzQ2c0Zmkrdz09IiwibWVkaWFMaW5rIjoiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vZG93bmxvYWQvc3RvcmFnZS92MS9iL3hiYW5kX3BhY2tldF9zdG9yZV9kZXYvby8yMDIwYXVnJTJGdGVzdCUyRjcyN181XzIwMjAwOTI0MDQzNzI0X3N0cml4XzIwMjAtU2VwLTI0LTA0LTM5LTAwP2dlbmVyYXRpb249MTYwMzg2MTYxMDgzNjk4Nlx1MDAyNmFsdD1tZWRpYSIsImNyYzMyYyI6IkY2M3dOdz09IiwiZXRhZyI6IkNQcm4xSXpDMXV3Q0VBRT0ifSwiYXR0cmlidXRlcyI6eyJidWNrZXRJZCI6InhiYW5kX3BhY2tldF9zdG9yZV9kZXYiLCJldmVudFRpbWUiOiIyMDIwLTEwLTI4VDA1OjA2OjUwLjgzNjY3NFoiLCJldmVudFR5cGUiOiJPQkpFQ1RfRklOQUxJWkUiLCJub3RpZmljYXRpb25Db25maWciOiJwcm9qZWN0cy9fL2J1Y2tldHMveGJhbmRfcGFja2V0X3N0b3JlX2Rldi9ub3RpZmljYXRpb25Db25maWdzLzMiLCJvYmplY3RHZW5lcmF0aW9uIjoiMTYwMzg2MTYxMDgzNjk4NiIsIm9iamVjdElkIjoiMjAyMGF1Zy90ZXN0LzcyN181XzIwMjAwOTI0MDQzNzI0X3N0cml4XzIwMjAtU2VwLTI0LTA0LTM5LTAwIiwicGF5bG9hZEZvcm1hdCI6IkpTT05fQVBJX1YxIn0sInB1Ymxpc2hUaW1lIjoiMjAyMC0xMC0yOCAwNTowNjo1MS4xMzYgKzAwMDAgVVRDIn0=\",\"datacontenttype\":\"application/json\",\"id\":\"66343235313038312d363237642d346565392d393937652d316166393037393763373761\",\"source\":\"gcp-pubsub-argo-test\",\"specversion\":\"1.0\",\"subject\":\"decode-rawdata\",\"time\":\"2020-10-28T05:06:51.182159974Z\",\"type\":\"pubsub\"}" timestamp:1603861611183153835 
```

**Comment by whynowy** [comment] 2020-10-28 08:19
I meant the log of EventSource POD.

**Comment by duluong** [comment] 2020-10-28 09:30
here you are
```
{"level":"info","ts":1603691416.0630586,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:251","msg":"Starting event source server...","eventSourceName":"gcp-pubsub-argo-test"}
{"level":"info","ts":1603691416.0637534,"logger":"argo-events.eventsource","caller":"driver/nats.go:92","msg":"NATS auth strategy: Token","eventSourceName":"gcp-pubsub-argo-test","clientID":"gcp-pubsub-argo-test-eventsource-j9tnk-c65779d56-s2sp6"}
{"level":"info","ts":1603691416.080008,"logger":"argo-events.eventsource","caller":"driver/nats.go:104","msg":"Connected to NATS server.","eventSourceName":"gcp-pubsub-argo-test","clientID":"gcp-pubsub-argo-test-eventsource-j9tnk-c65779d56-s2sp6"}
{"level":"info","ts":1603691416.083311,"logger":"argo-events.eventsource","caller":"driver/nats.go:117","msg":"Connected to NATS streaming server.","eventSourceName":"gcp-pubsub-argo-test","clientID":"gcp-pubsub-argo-test-eventsource-j9tnk-c65779d56-s2sp6"}
{"level":"info","ts":1603691416.0835514,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:333","msg":"Eventing server started.","eventSourceName":"gcp-pubsub-argo-test"}
{"level":"info","ts":1603691416.0837402,"logger":"argo-events.eventsource","caller":"gcppubsub/start.go:71","msg":"started processing the GCP Pub Sub event source...","eventSourceName":"gcp-pubsub-argo-test","eventSourceType":"pubsub","eventName":"decode-rawdata"}
{"level":"info","ts":1603691416.0838308,"logger":"argo-events.eventsource","caller":"gcppubsub/start.go:77","msg":"assuming all events have a json body...","eventSourceName":"gcp-pubsub-argo-test","eventSourceType":"pubsub","eventName":"decode-rawdata"}
{"level":"info","ts":1603691416.0839002,"logger":"argo-events.eventsource","caller":"gcppubsub/start.go:82","msg":"setting up a client to connect to PubSub...","eventSourceName":"gcp-pubsub-argo-test","eventSourceType":"pubsub","eventName":"decode-rawdata","topic":""}
{"level":"info","ts":1603691416.0844522,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:272","msg":"starting eventbus connection daemon...","eventSourceName":"gcp-pubsub-argo-test"}
{"level":"info","ts":1603691416.5452592,"logger":"argo-events.eventsource","caller":"gcppubsub/start.go:125","msg":"subscribing to PubSub topic...","eventSourceName":"gcp-pubsub-argo-test","eventSourceType":"pubsub","eventName":"decode-rawdata","topic":"","subscription":"sol-grdsys-datastore-downlink-packet-topic-sub"}
{"level":"info","ts":1603691416.5453017,"logger":"argo-events.eventsource","caller":"gcppubsub/start.go:127","msg":"listening for messages from PubSub...","eventSourceName":"gcp-pubsub-argo-test","eventSourceType":"pubsub","eventName":"decode-rawdata","topic":"","subscription":"sol-grdsys-datastore-downlink-packet-topic-sub"}
{"level":"info","ts":1603692925.8338797,"logger":"argo-events.eventsource","caller":"gcppubsub/start.go:129","msg":"received GCP PubSub Message from topic","eventSourceName":"gcp-pubsub-argo-test","eventSourceType":"pubsub","eventName":"decode-rawdata","topic":"","subscription":"sol-grdsys-datastore-downlink-packet-topic-sub"}
{"level":"info","ts":1603692925.8340437,"logger":"argo-events.eventsource","caller":"gcppubsub/start.go:146","msg":"dispatching event...","eventSourceName":"gcp-pubsub-argo-test","eventSourceType":"pubsub","eventName":"decode-rawdata","topic":"","subscription":"sol-grdsys-datastore-downlink-packet-topic-sub"}
{"level":"info","ts":1603692926.1324296,"logger":"argo-events.eventsource","caller":"gcppubsub/start.go:129","msg":"received GCP PubSub Message from topic","eventSourceName":"gcp-pubsub-argo-test","eventSourceType":"pubsub","eventName":"decode-rawdata","topic":"","subscription":"sol-grdsys-datastore-downlink-packet-topic-sub"}
{"level":"info","ts":1603692926.132512,"logger":"argo-events.eventsource","caller":"gcppubsub/start.go:146","msg":"dispatching event...","eventSourceName":"gcp-pubsub-argo-test","eventSourceType":"pubsub","eventName":"decode-rawdata","topic":"","subscription":"sol-grdsys-datastore-downlink-packet-topic-sub"}
{"level":"info","ts":1603861611.1132529,"logger":"argo-events.eventsource","caller":"gcppubsub/start.go:129","msg":"received GCP PubSub Message from topic","eventSourceName":"gcp-pubsub-argo-test","eventSourceType":"pubsub","eventName":"decode-rawdata","topic":"","subscription":"sol-grdsys-datastore-downlink-packet-topic-sub"}
{"level":"info","ts":1603861611.1134086,"logger":"argo-events.eventsource","caller":"gcppubsub/start.go:146","msg":"dispatching event...","eventSourceName":"gcp-pubsub-argo-test","eventSourceType":"pubsub","eventName":"decode-rawdata","topic":"","subscription":"sol-grdsys-datastore-downlink-packet-topic-sub"}
{"level":"info","ts":1603861611.18205,"logger":"argo-events.eventsource","caller":"gcppubsub/start.go:129","msg":"received GCP PubSub Message from topic","eventSourceName":"gcp-pubsub-argo-test","eventSourceType":"pubsub","eventName":"decode-rawdata","topic":"","subscription":"sol-grdsys-datastore-downlink-packet-topic-sub"}
{"level":"info","ts":1603861611.182133,"logger":"argo-events.eventsource","caller":"gcppubsub/start.go:146","msg":"dispatching event...","eventSourceName":"gcp-pubsub-argo-test","eventSourceType":"pubsub","eventName":"decode-rawdata","topic":"","subscription":"sol-grdsys-datastore-downlink-packet-topic-sub"}
```

**Comment by whynowy** [comment] 2020-10-28 17:38
@tmshn - Do you have any idea? It's 1.0.0 code, not including your latest pub/sub code change.

**Comment by whynowy** [comment] 2020-10-29 08:21
@duluong - Can you try following images to see if the issue still there?

Update `eventsource-controller` deployment.
```
        - name: EVENTSOURCE_IMAGE
          value: gcr.io/whynowy/eventsource:1.879
        image: gcr.io/whynowy/eventsource-controller:1.879
```

**Comment by duluong** [comment] 2020-10-30 01:07
@whynowy 
I've tried, but no change.

I think it is easy to reproduce.
So if you could do the test on your side, the problem will be solved quick.

**Comment by tmshn** [comment] 2020-10-31 04:22
I don't see the problem on my side with the similar setup, and it occurs consistently on your side, it seems the GCP Pub/Sub topic actually sends messages duplicatedly.

Could you try following tests?

1. See messages with another subscription
    - Create a new subscription to the topic you are using
    - Publish a message same way as you usually do
    - Do you see multiple messages on the new subscription? (easiest way is to check ” number of unacknowledged messages” on the monitoring page, or use `gcloud pubsub subscription pull` command to actually pull messages).
2. Publish a message using another tool
    - Publish a new message using `gcloud pubsub topic publish` command, not using your usual method, but with your usual setup
    - Does EventSouce pod see multiple messages?

**Comment by duluong** [comment] 2020-11-02 03:08
@tmshn @whynowy 
Thanks so much for your support 🙇‍♂️ 
Yeah, you are right. 
I've checked again in our environment and found the problem in infra setting.
Very sorry for the inconvenience.

If ok, let me close the issue.

**Comment by whynowy** [comment] 2020-11-02 05:42
Thanks @tmshn !

**Closed by whynowy** 2020-11-02 05:42 UTC
Labels: bug
