### ISSUE TITLE
authSecret field in webhook eventsource not working

### ISSUE THREAD

**Issue by philippe-boyd-3r** [argoproj/argo-events#835] opened 2020-08-13 15:34 UTC
> Based on https://github.com/argoproj/argo-events/blob/master/docs/webhook-authentication.md

**Describe the bug**
The `authSecret` field in webhook eventsource is not working. In fact, when deploying an eventsource with a webhook containing the `authSecret` field, it'll get removed once the resources is created in the cluster.

**To Reproduce**
Deploy Argo

```bash
kubectl create namespace argo
kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo/master/manifests/quick-start-postgres.yaml
```

Deploy Argo-events

```bash
kubectl create namespace argo-events
kubectl apply -f https://raw.githubusercontent.com/argoproj/argo-events/master/manifests/install.yaml
kubectl apply -n argo-events -f https://raw.githubusercontent.com/argoproj/argo-events/master/examples/eventbus/native.yaml
```

Create the secret

```bash
kubectl create secret generic my-webhook-token --from-literal=my-token=af3qqs321f2ddwf1e2e67dfda3fs
```

Deploy eventsource and sensor

```bash
cat <<EOF | kubectl apply -n argo-events -f -
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    example:
      authSecret:
        name: my-webhook-token
        key: my-token
      port: "12000"
      endpoint: /example
      method: POST
EOF
kubectl apply -n argo-events -f https://raw.githubusercontent.com/argoproj/argo-events/master/examples/sensors/webhook.yaml
```

View the eventsource

```bash
kubectl get -n argo-events eventsources.argoproj.io webhook -o yaml
```

The `authSecret` section is absent...

```yaml
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"EventSource","metadata":{"annotations":{},"name":"webhook","namespace":"argo-events"},"spec":{"service":{"ports":[{"port":12000,"targetPort":12000}]},"webhook":{"example":{"authSecret":{"key":"my-token","name":"my-webhook-token"},"endpoint":"/example","method":"POST","port":"12000"}}}}
  creationTimestamp: "2020-08-13T15:31:27Z"
  finalizers:
  - eventsource-controller
  generation: 2
  name: webhook
  namespace: argo-events
  resourceVersion: "1071"
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argo-events/eventsources/webhook
  uid: af8ecf20-3b7d-461a-bace-b48d163cea39
spec:
  service:
    ports:
    - port: 12000
      targetPort: 12000
  template:
    metadata: {}
  webhook:
    example:
      endpoint: /example
      method: POST
      port: "12000"
      url: ""
status:
  conditions:
  - lastTransitionTime: "2020-08-13T15:31:27Z"
    status: "True"
    type: Deployed
  - lastTransitionTime: "2020-08-13T15:31:27Z"
    status: "True"
    type: SourcesProvided
```

**Expected behavior**
The `authSecret` section should be in the event source

**Environment (please complete the following information):**
 - Kubernetes: v1.17.7
 - Argo: master
 - Argo Events: master

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment] 2020-08-13 16:26
This feature was not released in `v1.0.0-rc1`, stay tune. @philippe-boyd-3r

**Comment by whynowy** [comment] 2020-08-16 22:23
See v1.0.0-rc2

**Closed by whynowy** 2020-08-16 22:23 UTC

**Comment by shmargum** [comment] 2020-09-03 02:18
fyi i had to delete my event source then recreate it (kubectl apply did not trigger the change, i was also not seeing the authSecret field)
using 1.0.0-rc3

**Comment by whynowy** [comment] 2020-09-03 05:59
@shmargum - Can you give more detail? What does your spec look like?

**Comment by shmargum** [comment] 2020-09-03 15:18
I updated my eventbus controller, eventsource controller, and eventsource image from 0.17.10 to 1.0.0-rc3
and added
```yaml
authSecret:
  name: test-workflow
  key:  ARGO_WEBHOOK_SECRET
```
to the service and kubectl applied the files via kustomize (together)
there was no auth, and the `authSecret` field was not present on the event source when doing a kubectl get

when i deleted the event source and re-applied it was fine

**Comment by whynowy** [comment] 2020-09-03 15:58
So you are saying `kubectl apply` to an existing spec didn't work but `kubectl delete` and `kubectl apply` again worked, right? That seems to be weird, people do this kind of things many times every day... Can you reproduce it?

**Comment by shmargum** [comment] 2020-09-03 16:54
yes i can reproduce this.  this may be specifically when adding auth AND upgrading from 0.17 to 1.0.0-rc3
i do see this:
```yaml
  - name: auth-volume
    secret:
      defaultMode: 420
      items:
      - key: client-auth
        path: auth.yaml
      secretName: eventbus-default-client
```

but even if i delete the pod it spins back up with no auth

i have to delete the event source `kubectl delete es webhook`
and then reapply it to get it working

**Comment by whynowy** [comment] 2020-09-03 17:13
This `auth-volume` with `client-auth` is different from the one we talked about - `auth-secret` for webhook. This one is `eventbus` auth token for event sources (and sensors) to connect to event bus.
