### ISSUE TITLE
v1.0.0-rc1 Duplicate trigger executions 

### ISSUE THREAD

**Issue by terev** [argoproj/argo-events#850] opened 2020-08-28 05:44 UTC
**Describe the bug**
It appears a sensor with only one subscription and trigger is having duplicate trigger executions. The event source logs indicate that it's only publishing one msg to the nats event bus. But when the sensor receives it seems like the k8s trigger is being executed multiple times. As a result multiple k8s objects end up being created which is not desirable.

**To Reproduce**
Unsure how to reliably reproduce this. After deleting our existing sensor pod and publishing another message to pubsub the trigger seems to only have been executed once. Our event source subscribes to a pubsub topic and our sensor has one trigger that creates an argo workflow via the k8s trigger.

**Expected behavior**
At most one trigger execution for a given event.

**Screenshots**
#### Sensor logs:
```
{"level":"info","ts":1598575219.828351,"logger":"argo-events.sensor","caller":"sensors/listener.go:298","msg":"Dependency expression for trigger ******* before simlification: *******","sensorName":"*******"}
{"level":"info","ts":1598575219.8294034,"logger":"argo-events.sensor","caller":"sensors/listener.go:305","msg":"Dependency expression for trigger ******* after simlification: *******","sensorName":"*******"}
{"level":"info","ts":1598575219.8294897,"logger":"argo-events.sensor","caller":"sensors/listener.go:193","msg":"Sensor started.","sensorName":"*******"}
{"level":"info","ts":1598575219.8301706,"logger":"argo-events.sensor","caller":"driver/nats.go:92","msg":"NATS auth strategy: Token","sensorName":"*******","clientID":"client-2073791754"}
{"level":"info","ts":1598575219.9658506,"logger":"argo-events.sensor","caller":"driver/nats.go:104","msg":"Connected to NATS server.","sensorName":"*******","clientID":"client-2073791754"}
{"level":"info","ts":1598575219.97036,"logger":"argo-events.sensor","caller":"driver/nats.go:117","msg":"Connected to NATS streaming server.","sensorName":"*******","clientID":"client-2073791754"}
{"level":"info","ts":1598575219.9707575,"logger":"argo-events.sensor","caller":"sensors/listener.go:158","msg":"starting eventbus connection daemon for client client-2073791754...","sensorName":"*******"}
{"level":"info","ts":1598575219.9710104,"logger":"argo-events.sensor","caller":"sensors/listener.go:150","msg":"started to subscribe events for triggers [*******] with client client-2073791754","sensorName":"*******"}
{"level":"info","ts":1598575219.974745,"logger":"argo-events.sensor","caller":"driver/nats.go:156","msg":"Subscribed to subject eventbus-argo-events ...","sensorName":"*******","clientID":"client-2073791754"}
{"level":"info","ts":1598590170.6991246,"logger":"argo-events.sensor","caller":"standard-k8s/standar-k8s.go:163","msg":"creating the object...","sensorName":"*******"}
{"level":"info","ts":1598590170.6995637,"logger":"argo-events.sensor","caller":"standard-k8s/standar-k8s.go:163","msg":"creating the object...","sensorName":"*******"}
{"level":"info","ts":1598590170.7001216,"logger":"argo-events.sensor","caller":"standard-k8s/standar-k8s.go:163","msg":"creating the object...","sensorName":"*******"}
{"level":"info","ts":1598590170.6991982,"logger":"argo-events.sensor","caller":"standard-k8s/standar-k8s.go:163","msg":"creating the object...","sensorName":"*******"}
{"level":"info","ts":1598590170.8377492,"logger":"argo-events.sensor","caller":"standard-k8s/standar-k8s.go:163","msg":"creating the object...","sensorName":"*******"}
{"level":"info","ts":1598590170.8384159,"logger":"argo-events.sensor","caller":"standard-k8s/standar-k8s.go:163","msg":"creating the object...","sensorName":"*******"}
{"level":"info","ts":1598590171.2760425,"logger":"argo-events.sensor","caller":"standard-k8s/standar-k8s.go:163","msg":"creating the object...","sensorName":"*******"}
{"level":"info","ts":1598590170.6993852,"logger":"argo-events.sensor","caller":"standard-k8s/standar-k8s.go:163","msg":"creating the object...","sensorName":"*******"}
{"level":"info","ts":1598590170.699519,"logger":"argo-events.sensor","caller":"standard-k8s/standar-k8s.go:163","msg":"creating the object...","sensorName":"*******"}
{"level":"info","ts":1598590170.837516,"logger":"argo-events.sensor","caller":"standard-k8s/standar-k8s.go:163","msg":"creating the object...","sensorName":"*******"}
{"level":"info","ts":1598590172.212891,"logger":"argo-events.sensor","caller":"standard-k8s/standar-k8s.go:163","msg":"creating the object...","sensorName":"*******"}
{"level":"info","ts":1598590172.2137508,"logger":"argo-events.sensor","caller":"standard-k8s/standar-k8s.go:163","msg":"creating the object...","sensorName":"*******"}
{"level":"info","ts":1598590176.7628434,"logger":"argo-events.sensor","caller":"sensors/listener.go:247","msg":"successfully processed the trigger","sensorName":"*******","triggerName":"*******"}
{"level":"info","ts":1598590176.7674096,"logger":"argo-events.sensor","caller":"sensors/listener.go:247","msg":"successfully processed the trigger","sensorName":"*******","triggerName":"*******"}
{"level":"info","ts":1598590176.7675326,"logger":"argo-events.sensor","caller":"sensors/listener.go:247","msg":"successfully processed the trigger","sensorName":"*******","triggerName":"*******"}
{"level":"info","ts":1598590176.7682214,"logger":"argo-events.sensor","caller":"sensors/listener.go:247","msg":"successfully processed the trigger","sensorName":"*******","triggerName":"*******"}
{"level":"info","ts":1598590176.7682824,"logger":"argo-events.sensor","caller":"sensors/listener.go:247","msg":"successfully processed the trigger","sensorName":"*******","triggerName":"*******"}
{"level":"info","ts":1598590176.7685165,"logger":"argo-events.sensor","caller":"sensors/listener.go:247","msg":"successfully processed the trigger","sensorName":"*******","triggerName":"*******"}
{"level":"info","ts":1598590176.7756553,"logger":"argo-events.sensor","caller":"sensors/listener.go:247","msg":"successfully processed the trigger","sensorName":"*******","triggerName":"*******"}
{"level":"info","ts":1598590176.776444,"logger":"argo-events.sensor","caller":"sensors/listener.go:247","msg":"successfully processed the trigger","sensorName":"*******","triggerName":"*******"}
{"level":"info","ts":1598590176.7765648,"logger":"argo-events.sensor","caller":"sensors/listener.go:247","msg":"successfully processed the trigger","sensorName":"*******","triggerName":"*******"}
{"level":"info","ts":1598590176.7764866,"logger":"argo-events.sensor","caller":"sensors/listener.go:247","msg":"successfully processed the trigger","sensorName":"*******","triggerName":"*******"}
{"level":"info","ts":1598590176.7765672,"logger":"argo-events.sensor","caller":"sensors/listener.go:247","msg":"successfully processed the trigger","sensorName":"*******","triggerName":"*******"}
{"level":"info","ts":1598590176.7775786,"logger":"argo-events.sensor","caller":"sensors/listener.go:247","msg":"successfully processed the trigger","sensorName":"*******","triggerName":"*******"}
```
#### Event Source Logs:
```
{"level":"info","ts":1598575176.3333988,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:251","msg":"Starting event source server...","eventSourceName":"*******"}
{"level":"info","ts":1598575176.33432,"logger":"argo-events.eventsource","caller":"driver/nats.go:92","msg":"NATS auth strategy: Token","eventSourceName":"*******","clientID":"*******-eventsource-qbthl-59784f6c66-89nxg"}
{"level":"info","ts":1598575176.3391821,"logger":"argo-events.eventsource","caller":"driver/nats.go:104","msg":"Connected to NATS server.","eventSourceName":"*******","clientID":"*******-eventsource-qbthl-59784f6c66-89nxg"}
{"level":"info","ts":1598575176.363162,"logger":"argo-events.eventsource","caller":"driver/nats.go:117","msg":"Connected to NATS streaming server.","eventSourceName":"*******","clientID":"*******-eventsource-qbthl-59784f6c66-89nxg"}
{"level":"info","ts":1598575176.363233,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:333","msg":"Eventing server started.","eventSourceName":"*******"}
{"level":"info","ts":1598575176.363447,"logger":"argo-events.eventsource","caller":"gcppubsub/start.go:71","msg":"started processing the GCP Pub Sub event source...","eventSourceName":"*******","eventSourceType":"pubsub","eventName":"*******"}
{"level":"info","ts":1598575176.3634806,"logger":"argo-events.eventsource","caller":"gcppubsub/start.go:77","msg":"assuming all events have a json body...","eventSourceName":"*******","eventSourceType":"pubsub","eventName":"*******"}
{"level":"info","ts":1598575176.363532,"logger":"argo-events.eventsource","caller":"gcppubsub/start.go:82","msg":"setting up a client to connect to PubSub...","eventSourceName":"*******","eventSourceType":"pubsub","eventName":"*******","topic":"*******"}
{"level":"info","ts":1598575176.366054,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:272","msg":"starting eventbus connection daemon...","eventSourceName":"*******"}
{"level":"info","ts":1598575176.8224916,"logger":"argo-events.eventsource","caller":"gcppubsub/start.go:125","msg":"subscribing to PubSub topic...","eventSourceName":"*******","eventSourceType":"pubsub","eventName":"*******","topic":"******","subscription":"*******-1210117494"}
{"level":"info","ts":1598575176.8225484,"logger":"argo-events.eventsource","caller":"gcppubsub/start.go:127","msg":"listening for messages from PubSub...","eventSourceName":"*******","eventSourceType":"pubsub","eventName":"*******","topic":"*******","subscription":"*******-1210117494"}
{"level":"info","ts":1598590148.637096,"logger":"argo-events.eventsource","caller":"gcppubsub/start.go:129","msg":"received GCP PubSub Message from topic","eventSourceName":"*******","eventSourceType":"pubsub","eventName":"*******","topic":"*******","subscription":"*******-1210117494"}
{"level":"info","ts":1598590151.0076425,"logger":"argo-events.eventsource","caller":"gcppubsub/start.go:146","msg":"dispatching event...","eventSourceName":"*******","eventSourceType":"pubsub","eventName":"*******","topic":"*******","subscription":"*******-1210117494"}
```

**Environment (please complete the following information):**
 - Kubernetes: v1.15
 - Argo: v2.9.5
 - Argo Events: v1.0.0-rc1

**Additional context**

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment] 2020-08-28 08:23
I guess you might have done something like:

1. Created an EventSource, and a sensor;
2. Deleted the Sensor, or for some reason the Sensor pod didn't run for a while, however the EventSource still generated events (i.e. a Calendar);
3. Re-created the Sensor, or the sensor POD was back, then you saw the trigger was executed multiple times.

This is an expected behavior, that if your Sensor POD is gone/crashed for a while, you don't lose any message. 

The sensor does [durable subscription](https://docs.nats.io/developing-with-nats-streaming/durables) to the NATS Streaming channel with start position `StartPosition_LastReceived`, which means it starts at the position where the NATS server last received message, however, after that, if the subscription is closed for whatever reason, it will use a NATS maintained position for that `clientID` and `durableName` as the start position. 

We use a combination of `sensorName` and `triggerName` as clientID and durableName to subscribe, so if you recreate the sensor with same sensorName and triggerName, it will consider it is same client, hence you get all the messages you missed.

Let me know if you have a different case.

@terev

**Comment by terev** [comment] 2020-08-28 15:26
@whynowy We don't think any of those theories align with what we witnessed. Our situation was more like our sensor and event source pods were sitting there running, we published a message and we got duplicate trigger executions. After noticing the duplicate trigger executions we published another message and reproduced this issue. The timestamps in the posted logs indicate that the sensor pod was running when the event source received the event.

**Comment by whynowy** [comment] 2020-08-28 16:42
Both the eventsource and sensor log can not tell how many messages are already in the EventBus (the message expiration time is 72 hours), it only shows what happened after the services start. From the Sensor log, what I can tell is, at the time the Sensor PODs started, there were 12 messages matching the trigger dependency conditions, if you create a new sensor object with different name but listening to same event source, I believe it will also trigger same times actions - this could be a way to troubleshoot.

If you can reproduce it, there's another way to troubleshoot. Each message in the EventBus has an unique field `id` in `context`, you can follow the example below, use `contextKey` to tell if they are the same message. Another field context `time` also can help.  Please let me know the result.
```
          parameters:
            - src:
                dependencyName: test-dep
                contextKey: id
              dest: xxxxx
```

https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/tutorials/02-parameterization/sensor-01.yaml

**Comment by terev** [comment] 2020-08-29 06:08
I've been attempting to reproduce this but have not had any luck so far. However I still believe the fact that we were able to reproduce the same issue a few minutes after initially noticing it shows that there's something up. I've interlaced the sensor and event source logs below to make it easier to see there was only ever one gcp pubsub message received by the event source and when it's received by the sensor there are many trigger executions.

The following list is generated by this command:
```bash
echo '...' | jq -rc 'sort_by(.ts) | map(.ts |=  todate | . | tostring) | join("\n")'
```

interlaced logs sorted by ts:
```json
{"level":"info","ts":"2020-08-28T00:39:36Z","logger":"argo-events.eventsource","caller":"eventsources/eventing.go:251","msg":"Starting event source server...","eventSourceName":"*******"}
{"level":"info","ts":"2020-08-28T00:39:36Z","logger":"argo-events.eventsource","caller":"driver/nats.go:92","msg":"NATS auth strategy: Token","eventSourceName":"*******","clientID":"*******-eventsource-qbthl-59784f6c66-89nxg"}
{"level":"info","ts":"2020-08-28T00:39:36Z","logger":"argo-events.eventsource","caller":"driver/nats.go:104","msg":"Connected to NATS server.","eventSourceName":"*******","clientID":"*******-eventsource-qbthl-59784f6c66-89nxg"}
{"level":"info","ts":"2020-08-28T00:39:36Z","logger":"argo-events.eventsource","caller":"driver/nats.go:117","msg":"Connected to NATS streaming server.","eventSourceName":"*******","clientID":"*******-eventsource-qbthl-59784f6c66-89nxg"}
{"level":"info","ts":"2020-08-28T00:39:36Z","logger":"argo-events.eventsource","caller":"eventsources/eventing.go:333","msg":"Eventing server started.","eventSourceName":"*******"}
{"level":"info","ts":"2020-08-28T00:39:36Z","logger":"argo-events.eventsource","caller":"gcppubsub/start.go:71","msg":"started processing the GCP Pub Sub event source...","eventSourceName":"*******","eventSourceType":"pubsub","eventName":"*******"}
{"level":"info","ts":"2020-08-28T00:39:36Z","logger":"argo-events.eventsource","caller":"gcppubsub/start.go:77","msg":"assuming all events have a json body...","eventSourceName":"*******","eventSourceType":"pubsub","eventName":"*******"}
{"level":"info","ts":"2020-08-28T00:39:36Z","logger":"argo-events.eventsource","caller":"gcppubsub/start.go:82","msg":"setting up a client to connect to PubSub...","eventSourceName":"*******","eventSourceType":"pubsub","eventName":"*******","topic":"*******"}
{"level":"info","ts":"2020-08-28T00:39:36Z","logger":"argo-events.eventsource","caller":"eventsources/eventing.go:272","msg":"starting eventbus connection daemon...","eventSourceName":"*******"}
{"level":"info","ts":"2020-08-28T00:39:36Z","logger":"argo-events.eventsource","caller":"gcppubsub/start.go:125","msg":"subscribing to PubSub topic...","eventSourceName":"*******","eventSourceType":"pubsub","eventName":"*******","topic":"******","subscription":"*******-1210117494"}
{"level":"info","ts":"2020-08-28T00:39:36Z","logger":"argo-events.eventsource","caller":"gcppubsub/start.go:127","msg":"listening for messages from PubSub...","eventSourceName":"*******","eventSourceType":"pubsub","eventName":"*******","topic":"*******","subscription":"*******-1210117494"}
{"level":"info","ts":"2020-08-28T00:40:19Z","logger":"argo-events.sensor","caller":"sensors/listener.go:298","msg":"Dependency expression for trigger ******* before simlification: *******","sensorName":"*******"}
{"level":"info","ts":"2020-08-28T00:40:19Z","logger":"argo-events.sensor","caller":"sensors/listener.go:305","msg":"Dependency expression for trigger ******* after simlification: *******","sensorName":"*******"}
{"level":"info","ts":"2020-08-28T00:40:19Z","logger":"argo-events.sensor","caller":"sensors/listener.go:193","msg":"Sensor started.","sensorName":"*******"}
{"level":"info","ts":"2020-08-28T00:40:19Z","logger":"argo-events.sensor","caller":"driver/nats.go:92","msg":"NATS auth strategy: Token","sensorName":"*******","clientID":"client-2073791754"}
{"level":"info","ts":"2020-08-28T00:40:19Z","logger":"argo-events.sensor","caller":"driver/nats.go:104","msg":"Connected to NATS server.","sensorName":"*******","clientID":"client-2073791754"}
{"level":"info","ts":"2020-08-28T00:40:19Z","logger":"argo-events.sensor","caller":"driver/nats.go:117","msg":"Connected to NATS streaming server.","sensorName":"*******","clientID":"client-2073791754"}
{"level":"info","ts":"2020-08-28T00:40:19Z","logger":"argo-events.sensor","caller":"sensors/listener.go:158","msg":"starting eventbus connection daemon for client client-2073791754...","sensorName":"*******"}
{"level":"info","ts":"2020-08-28T00:40:19Z","logger":"argo-events.sensor","caller":"sensors/listener.go:150","msg":"started to subscribe events for triggers [*******] with client client-2073791754","sensorName":"*******"}
{"level":"info","ts":"2020-08-28T00:40:19Z","logger":"argo-events.sensor","caller":"driver/nats.go:156","msg":"Subscribed to subject eventbus-argo-events ...","sensorName":"*******","clientID":"client-2073791754"}
{"level":"info","ts":"2020-08-28T04:49:08Z","logger":"argo-events.eventsource","caller":"gcppubsub/start.go:129","msg":"received GCP PubSub Message from topic","eventSourceName":"*******","eventSourceType":"pubsub","eventName":"*******","topic":"*******","subscription":"*******-1210117494"}
{"level":"info","ts":"2020-08-28T04:49:11Z","logger":"argo-events.eventsource","caller":"gcppubsub/start.go:146","msg":"dispatching event...","eventSourceName":"*******","eventSourceType":"pubsub","eventName":"*******","topic":"*******","subscription":"*******-1210117494"}
{"level":"info","ts":"2020-08-28T04:49:30Z","logger":"argo-events.sensor","caller":"standard-k8s/standar-k8s.go:163","msg":"creating the object...","sensorName":"*******"}
{"level":"info","ts":"2020-08-28T04:49:30Z","logger":"argo-events.sensor","caller":"standard-k8s/standar-k8s.go:163","msg":"creating the object...","sensorName":"*******"}
{"level":"info","ts":"2020-08-28T04:49:30Z","logger":"argo-events.sensor","caller":"standard-k8s/standar-k8s.go:163","msg":"creating the object...","sensorName":"*******"}
{"level":"info","ts":"2020-08-28T04:49:30Z","logger":"argo-events.sensor","caller":"standard-k8s/standar-k8s.go:163","msg":"creating the object...","sensorName":"*******"}
{"level":"info","ts":"2020-08-28T04:49:30Z","logger":"argo-events.sensor","caller":"standard-k8s/standar-k8s.go:163","msg":"creating the object...","sensorName":"*******"}
{"level":"info","ts":"2020-08-28T04:49:30Z","logger":"argo-events.sensor","caller":"standard-k8s/standar-k8s.go:163","msg":"creating the object...","sensorName":"*******"}
{"level":"info","ts":"2020-08-28T04:49:30Z","logger":"argo-events.sensor","caller":"standard-k8s/standar-k8s.go:163","msg":"creating the object...","sensorName":"*******"}
{"level":"info","ts":"2020-08-28T04:49:30Z","logger":"argo-events.sensor","caller":"standard-k8s/standar-k8s.go:163","msg":"creating the object...","sensorName":"*******"}
{"level":"info","ts":"2020-08-28T04:49:30Z","logger":"argo-events.sensor","caller":"standard-k8s/standar-k8s.go:163","msg":"creating the object...","sensorName":"*******"}
{"level":"info","ts":"2020-08-28T04:49:31Z","logger":"argo-events.sensor","caller":"standard-k8s/standar-k8s.go:163","msg":"creating the object...","sensorName":"*******"}
{"level":"info","ts":"2020-08-28T04:49:32Z","logger":"argo-events.sensor","caller":"standard-k8s/standar-k8s.go:163","msg":"creating the object...","sensorName":"*******"}
{"level":"info","ts":"2020-08-28T04:49:32Z","logger":"argo-events.sensor","caller":"standard-k8s/standar-k8s.go:163","msg":"creating the object...","sensorName":"*******"}
{"level":"info","ts":"2020-08-28T04:49:36Z","logger":"argo-events.sensor","caller":"sensors/listener.go:247","msg":"successfully processed the trigger","sensorName":"*******","triggerName":"*******"}
{"level":"info","ts":"2020-08-28T04:49:36Z","logger":"argo-events.sensor","caller":"sensors/listener.go:247","msg":"successfully processed the trigger","sensorName":"*******","triggerName":"*******"}
{"level":"info","ts":"2020-08-28T04:49:36Z","logger":"argo-events.sensor","caller":"sensors/listener.go:247","msg":"successfully processed the trigger","sensorName":"*******","triggerName":"*******"}
{"level":"info","ts":"2020-08-28T04:49:36Z","logger":"argo-events.sensor","caller":"sensors/listener.go:247","msg":"successfully processed the trigger","sensorName":"*******","triggerName":"*******"}
{"level":"info","ts":"2020-08-28T04:49:36Z","logger":"argo-events.sensor","caller":"sensors/listener.go:247","msg":"successfully processed the trigger","sensorName":"*******","triggerName":"*******"}
{"level":"info","ts":"2020-08-28T04:49:36Z","logger":"argo-events.sensor","caller":"sensors/listener.go:247","msg":"successfully processed the trigger","sensorName":"*******","triggerName":"*******"}
{"level":"info","ts":"2020-08-28T04:49:36Z","logger":"argo-events.sensor","caller":"sensors/listener.go:247","msg":"successfully processed the trigger","sensorName":"*******","triggerName":"*******"}
{"level":"info","ts":"2020-08-28T04:49:36Z","logger":"argo-events.sensor","caller":"sensors/listener.go:247","msg":"successfully processed the trigger","sensorName":"*******","triggerName":"*******"}
{"level":"info","ts":"2020-08-28T04:49:36Z","logger":"argo-events.sensor","caller":"sensors/listener.go:247","msg":"successfully processed the trigger","sensorName":"*******","triggerName":"*******"}
{"level":"info","ts":"2020-08-28T04:49:36Z","logger":"argo-events.sensor","caller":"sensors/listener.go:247","msg":"successfully processed the trigger","sensorName":"*******","triggerName":"*******"}
{"level":"info","ts":"2020-08-28T04:49:36Z","logger":"argo-events.sensor","caller":"sensors/listener.go:247","msg":"successfully processed the trigger","sensorName":"*******","triggerName":"*******"}
{"level":"info","ts":"2020-08-28T04:49:36Z","logger":"argo-events.sensor","caller":"sensors/listener.go:247","msg":"successfully processed the trigger","sensorName":"*******","triggerName":"*******"}
```

**Comment by whynowy** [comment] 2020-08-29 07:56
@terev - As I mentioned above, the log does not represent how many messages were in the EventBus before that sensor POD started. 

If the scenario you saw happened no earlier than 72 hours ago, here is the way to troubleshoot (if you are interested in), 

1. Run `kubectl get secret eventbus-default-client -ojsonpath='{.data.client-auth}' | base64 --decode | awk -F\" '{print $2}'`, you will get the token to access EventBus.

2. Start a `nats-box` pod for debugging
```
kubectl run -i --rm --tty nats-box --image=synadia/nats-box --restart=Never
```
3. Within the `nats-box` POD, replace `{TOKEN}` and `{your-namespace}`, run `/usr/local/bin/./stan-sub -s nats://{TOKEN}@eventbus-default-stan-svc:4222 -c eventbus-default eventbus-{your-namespace} -all`

You will get all the messages in the last 72 hours, each of the message looks like below, you can `base64` decode the `data` field for troubleshooting.

```
[#16058] Received: sequence:21464 subject:"eventbus-argo-events" data:"{\"data_base64\":\"eyJldmVudFRpbWUiOiIyMDIwLTA4LTI4IDA0OjM2OjQ0LjAwMDA5MjE1NSArMDAwMCBVVEMgbT0rMzYwOTkuOTc2ODE5NzQzIn0=\",\"datacontenttype\":\"application/json\",\"id\":\"31616664323334302d303264372d343663302d396636662d326234616132383561646536\",\"source\":\"calendar\",\"specversion\":\"1.0\",\"subject\":\"example2\",\"time\":\"2020-08-28T04:36:44.000207112Z\",\"type\":\"calendar\"}" timestamp:1598589404000764639
```

**Comment by terev** [comment] 2020-08-29 10:03
@whynowy oh very cool thank you for this, it's quite useful

After receiving all of the events I'm able to confirm that there's only one message in the time period destined for that sensor.

**Comment by whynowy** [comment] 2020-08-29 15:29
Well, the time period really does not mean anything. Did you have any message before that `period` destined for that `eventSourceName` and `eventName`?

**Comment by terev** [comment] 2020-08-29 19:58
@whynowy There are 2 messages but they're from 2 days before and i know they were successfully processed. I should be clear that we applied a change to the sensor object and the pod was recreated by the controller that's why the logs indicate it was started soon before receiving an event. We then published a pubsub message and saw the duplicate trigger executions.

One thing i find interesting in the sensor logs (posted in the issue description) is it looks like there were parallel executions of the trigger action. Looking at the timestamps they appear out of order:

```
{"level":"info","ts":1598590170.7001216,"logger":"argo-events.sensor","caller":"standard-k8s/standar-k8s.go:163","msg":"creating the object...","sensorName":"*******"}
{"level":"info","ts":1598590170.6991982,"logger":"argo-events.sensor","caller":"standard-k8s/standar-k8s.go:163","msg":"creating the object...","sensorName":"*******"}
```

Also it seems like many receives occurred one after another.

**Comment by whynowy** [comment] 2020-08-30 00:26
There might be more than 2 messages because it had been 1+ days after you raised this issue, and they might have been automatically deleted due to 72h expiration.

For every action execution, it is done with a GoRoutine, which means if there are 10 messages in place, and 10 GoRoutines will be initiated, they will not follow the queued order.

**Comment by terev** [comment] 2020-08-30 08:41
If there were messages waiting to be received in the event bus wouldn't the sensor have received them right away when it subscribed at `{"level":"info","ts":"2020-08-28T00:40:19Z","logger":"argo-events.sensor","caller":"driver/nats.go:156","msg":"Subscribed to subject eventbus-argo-events ...","sensorName":"*******","clientID":"client-2073791754"}` ? 

But that's not what happened there's around a 4 hour gap between when the sensor started and when the first event was received. The first indication of an event being received correlates with the gcp pubsub event being received so the two most likely are related. So I don't see how there could have been 11 other events out of no where received at the same time as the pubsub event.

**Comment by whynowy** [comment] 2020-08-31 20:27
@terev - I don't understand why... please let me know if you manage to reproduce.

**Comment by terev** [comment] 2020-08-31 20:47
@whynowy that's fair it almost seems related to the nats streaming client in some way. possibly the way it's configured but it looks reasonable to me. the 1 second manual ack timeout could be a bit short for the k8s trigger, not sure though. will continue trying to reproduce and i'll let you know if i discover anything

**Comment by whynowy** [comment] 2020-08-31 22:27
I have the same feeling (about the streaming client)...

Right, we do `go action(messages)` so it does not block there before `Ack()`. We can slightly increase ack deadline a little bit anyways.

**Comment by whynowy** [comment] 2020-08-31 23:56
Create an issue for `ExactOne` triggering.

https://github.com/argoproj/argo-events/issues/853

**Comment by terev** [comment] 2020-09-01 00:07
Very cool i was wondering about doing this myself. Seems like a good safeguard to have in place :+1:

**Comment by whynowy** [comment] 2020-09-03 06:22
> Very cool i was wondering about doing this myself. Seems like a good safeguard to have in place 👍

@terev - would you like to work on that as well?

**Closed** 2020-09-25 21:59 UTC
Labels: bug
