### ISSUE TITLE
Google Cloud Pub/Sub

### ISSUE THREAD

**Issue by theomessin** [argoproj/argo-events#313] opened 2019-07-25 16:34 UTC
Do you still need the credentials file if you're running Argo from within GKE?
Shouldn't the Compute Engine service account be used by default?

**Comment by meftasadat** [comment] 2019-07-25 16:56
I am having some issues with the PubSub example even though I have verified I am using the credential file correctly. The issue is - the workflow is not getting triggered when I publish a msg

**Comment by VaibhavPage** [comment] 2019-07-26 11:44
what are the logs for your gateway pod?

**Comment by meftasadat** [comment] 2019-07-26 13:51
@VaibhavPage Thanks for taking a look. Here are the gateway pods log:

`kubectl logs gcp-pubsub-gateway -n argo-events -c gcp-pubsub-events`
starting gateway server

`kubectl logs gcp-pubsub-gateway -n argo-events -c gateway-client`


^ I see no logs from the gateway-client container

**Comment by Rahul2929** [comment] 2019-08-01 10:53
I am hitting the same issue as mentioned by @meftasadat, I am posting logs and my k8 configuration.

`kubectl logs gcp-pubsub-gateway -c gcp-pubsub-events -n argo-events
starting gateway server
INFO[2019-08-01 09:20:05] operating on event source                    
ERRO[2019-08-01 09:20:05] error occurred while getting event from event source  error="pubsub: cannot read credentials file: read /gcp-pubsub-creds-dir: is a directory" event-source=example-1
INFO[2019-08-01 09:23:13] operating on event source                    
INFO[2019-08-01 09:23:13] creating GCP PubSub topic                     event-source=example-1 topic=test
INFO[2019-08-01 09:23:14] subscribing to GCP PubSub topic               event-source=example-1 topic=test
ERRO[2019-08-01 09:23:14] error occurred while getting event from event source  error="rpc error: code = InvalidArgument desc = Invalid resource name given (name=projects/starry-academy-177207/subscriptions/3053350375). Refer to https://cloud.google.com/pubsub/docs/admin#resource_names for more information." event-source=example-1`

`kubectl logs gcp-pubsub-gateway -c gateway-client -n argo-events
INFO[2019-08-01 09:20:05] detected configmap addition                   name=gcp-pubsub-configmap
INFO[2019-08-01 09:20:05] event source                                  config-key=example-1 config-value="# id of your project\nprojectId: \"starry-academy-177207\"\n# topic name\ntopic: \"test\"\n# Refers to the credential file that is mounted in the gateway pod.\n# ./validate.go is just a placeholder to make tests pass. Please place the path to actual credentials file :)\ncredentialsFile: \"/gcp-pubsub-creds-dir\"" hash=1673255817
INFO[2019-08-01 09:20:05] state of the connection                       state=READY
INFO[2019-08-01 09:20:05] stale event sources                           event-source="[]"
INFO[2019-08-01 09:20:05] new event sources                             event-source="[1673255817]"
INFO[2019-08-01 09:20:05] activating new event source                   event-source=example-1
INFO[2019-08-01 09:20:05] event source is valid                        
INFO[2019-08-01 09:20:05] started listening to events from gateway server 
INFO[2019-08-01 09:20:05] received a gateway state update notification 
INFO[2019-08-01 09:20:05] node                                          node-name=example-1
INFO[2019-08-01 09:20:05] node is running                               node-message=event_source_is_running node-name=example-1`

k8 resource.yaml file: 

[test.txt](https://github.com/argoproj/argo-events/files/3456283/test.txt)

**Comment by meftasadat** [comment] 2019-08-01 13:23
@Rahul2929 it seems like you did not create the k8s secret with your GCP SA JSON file

**Comment by Rahul2929** [comment] 2019-08-01 13:31
No @meftasadat I have created the secret  and I verified its working too.
Here is the get secrets command output from the cluster
```
kubectl get secrets -n argo-events
NAME                         TYPE                                  DATA   AGE
gcp-pubsub                   Opaque                                1      26h
```

**Comment by Rahul2929** [comment] 2019-08-02 06:05
> I am having some issues with the PubSub example even though I have verified I am using the credential file correctly. The issue is - the workflow is not getting triggered when I publish a msg
> 
> my k8s resources yaml file:
> [test.txt](https://github.com/argoproj/argo-events/files/3432570/test.txt)
> 
> logs:
> ![image](https://user-images.githubusercontent.com/15067435/61893948-4dee9e80-aedd-11e9-85f9-9f46f88f0311.png)

@meftasadat your Gateway eventSource should have value "gcp-pubsub-configmap" and not "gcp-pubsub-event-source", since according to doc
```eventSource: Refers to K8s configmap that holds the list of event sources. You can use namespace/configmap-name syntax to refer the configmap in a different namespace.```

Can you please try once after this change.

**Comment by meftasadat** [comment] 2019-08-02 14:51
@Rahul2929 Thanks for taking a look into my issue, it fixed the initial issue, but now I am getting the same error as you 

`INFO[2019-08-02 14:43:46] operating on event source                    
INFO[2019-08-02 14:43:46] creating GCP PubSub topic                     event-source=example-1 topic=argo
INFO[2019-08-02 14:43:48] subscribing to GCP PubSub topic               event-source=example-1 topic=argo
ERRO[2019-08-02 14:43:48] error occurred while getting event from event source  error="rpc error: code = InvalidArgument desc = Invalid resource name given (name=projects/<gcp_project_name>/subscriptions/3829177571). Refer to https://cloud.google.com/pubsub/docs/admin#resource_names for more information." event-source=example-1`

**Comment by jtmiclat** [comment] 2019-08-02 16:11
To be more correct subscription names can has to start with a letter as mentioned in https://cloud.google.com/pubsub/docs/admin. 

```
The relative-name must:
...
+ Start with a letter 
...

The one being generated purely uses event.id. 
https://github.com/argoproj/argo-
events/blob/master/gateways/community/gcp-pubsub/start.go#L70

I suggest there should be a prefix the name of event-source or gateway name to the subscribers topic.

**Comment by VaibhavPage** [comment] 2019-08-02 17:07
@meftasadat you can check the `id` of your event source withing gateway `status` using `kubectl get gateway <gateway-name> -o yaml`. 

If it starts with a number then I believe as per https://cloud.google.com/pubsub/docs/admin#resource_names it is going to fail.

@jtmiclat yes. that would be a good fix.

**Comment by Rahul2929** [comment] 2019-08-05 11:55
@VaibhavPage tried with the fresh code, still encountering same issue seems like docker images need to be updated.
Can you please let me know when the image will be updated.

**Comment by VaibhavPage** [comment] 2019-08-06 01:14
latest patch is pushed, you can try argoproj/gcp-pubsub-gateway:v0.9.4

**Comment by VaibhavPage** [comment] 2019-10-05 20:28
Closing this issue for now. let me know if you still face the issue.

**Closed by VaibhavPage** 2019-10-05 20:28 UTC
Labels: needs investigation
