### ISSUE TITLE
Is it Possible to trigger on incoming amqp payload data state

### ISSUE THREAD

**Issue by emichaf** [argoproj/argo-events#165] opened 2019-02-05 15:13 UTC
Validating argo-events with amqp and wonder if it's possble to trigger flows based on incoming amqp event data payload? via gateway watchers or sensor's triggers or similar...

**Comment by VaibhavPage** [comment] 2019-02-05 17:13
You can basically apply `data filter` on event data and if payload passes filter then only sensor will trigger workflow/s. 

https://github.com/argoproj/argo-events/blob/master/examples/sensors/data-filter-webhook.yaml

With v0.8(will be released in next week), you can apply boolean circuit expression for dependencies with conjunction with filters. Maybe this will help you define which workflows to trigger to finer level. 

https://github.com/argoproj/argo-events/blob/master/examples/sensors/webhook-http-dependency-groups.yaml

**Comment by emichaf** [comment] 2019-02-06 13:12
Tried the sensor data filter (see below). Incoming JSON payload (AMQP) data.gitIdentifier.repoName=ms-frontend then the workflow should be triggered, but the workflow is triggered even if a change ms-frontend....   

Sensor:
..
     port: "9300"  
  dependencies:
    - name: "amqp-gateway:foo"
      filters:
        name: "data-filter"
        data:
          dataFilters:
            - path: data.gitIdentifier.repoName
              type: string
              value: ms-frontend
...

**Comment by VaibhavPage** [comment] 2019-02-06 17:27
looks like indentation is not valid, shouldn't it be 


```
port: "9300"
dependencies:
- name: "amqp-gateway:foo"
filters:
name: "data-filter"
data:
dataFilters:
- path: data.gitIdentifier.repoName
  type: string
  value: "ms-frontend"
```

If indentation is correct in sensor spec, can you add double quotes around ms-frontend

**Comment by emichaf** [comment] 2019-02-08 12:17
Tried with double quotes around ms-frontend, but it did not help!

apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: amqp-sensor
  labels:
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
spec:
  repeat: true
  deploySpec:
    containers:
      - name: "sensor"
        image: "argoproj/sensor"
        imagePullPolicy: Always
    serviceAccountName: argo-events-sa
  eventProtocol:
    type: "HTTP"
    http:
      port: "9300"  
  dependencies:
    - name: "amqp-gateway:foo"
      filters:
        name: "data-filter"
        data:
          dataFilters:
            - path: data.gitIdentifier.repoName
              type: string
              value: "ms-frontend"
  triggers:
    - name: argo-workflow
      resource:
        namespace: cx
        group: argoproj.io
        version: v1alpha1
        kind: Workflow
                # The parameters from the workflow are overridden by the webhook's message
        parameters:

......

**Comment by emichaf** [comment] 2019-02-12 21:52
Any ideas?

**Comment by VaibhavPage** [comment] 2019-02-12 22:14
I'll try to reproduce it.

**Comment by VaibhavPage** [comment] 2019-02-14 00:29
I can see the data filters are failing, this bug was introduced in last release. I have put a fix in https://github.com/argoproj/argo-events/tree/enhance-data-filter

**Comment by emichaf** [comment] 2019-02-14 07:19
Great, will this bugfix be included in v0.8 ?

**Comment by VaibhavPage** [comment] 2019-02-14 10:34
yup, it'll be a part of v0.8

**Comment by emichaf** [comment] 2019-02-14 10:58
Any why of forcing AMQP Gateway to restart or re-try to connect to exchange until RabbitMQ is up and running, now the AMQP GateWay pod is only restarting once ?

**Comment by VaibhavPage** [comment] 2019-02-14 11:06
Usually the amqp gateway expects to have RabbitMQ up and running so that it can connect to it. One of the features that are being added to v0.8 is that you'll be able to pass an exponential backoff option in event source configuration (gateway configmap) when it tries to connect to RabbitMQ.

**Comment by emichaf** [comment] 2019-02-14 11:24
Sounds great! 
When do you plan to release v0.8?

**Comment by VaibhavPage** [comment] 2019-02-14 11:41
most probably by end of this week.

**Comment by emichaf** [comment] 2019-02-18 19:36
Do you plan to release v0.8 this week?

**Comment by VaibhavPage** [comment] 2019-02-18 21:15
v0.8 release got delayed by a week due to some ongoing enhancements. But the feature related to connection backoff and bug fix for data filters are available in sensor image v0.7.2. Make sure to change sensor controller image to 0.7.2 as well.

https://github.com/argoproj/argo-events/blob/master/examples/sensors/data-filter-webhook.yaml

**Comment by emichaf** [comment] 2019-02-21 15:50
Tried sensor & sensor controller v0.7.3, and the datafiltering is working, but amqp connection to RabbitMQ is not working if rabbitMQ is deployed after amqp gateway, when redoplyoing amqp gateway after rabbitMQ started the queue is created and working!

Any new parameter for amqp sensor to retry connection, or anything that's needs to be configured for amqp gateway ? Any new  versions required for argoproj/gateway-client, argoproj/amqp-gateway ??

**Comment by VaibhavPage** [comment] 2019-02-22 16:14
Yeah, you need to provide the `backoff` option in gateway configmap. The configmap with `backoff` will like following - 

```
url: <url>
exchangeName: <exchange-name>
exchangeType: fanout
routingKey: <routing-key>
backoff:
  duration: 10       # 10 seconds
  steps: 5
  factor: 1.0

```

You can define exponential backoff by changing `factor`. You can find more information on `backoff` [here](https://github.com/kubernetes/apimachinery/blob/450d01ad5771972f60ff23d8f7c6df3211cffbcf/pkg/util/wait/wait.go#L207)

**Comment by emichaf** [comment] 2019-02-24 15:56
Worked perfectly after changing the amqp gateway image to version v0.7.2 (argoproj/amqp-gateway:v0.7.2)

**Comment by VaibhavPage** [comment] 2019-02-26 15:17
Can we close this issue?

**Closed** 2019-02-28 23:58 UTC
